package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Accessgroupldapgroups generated by hbm2java
 */
@Entity
@Table(name = "accessgroupldapgroups", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"rargroup", "ldapgroup" }))
public class Accessgroupldapgroups implements java.io.Serializable {

	private int id;
	private Ldapgroups ldapgroups;
	private Rargroup rargroup;

	public Accessgroupldapgroups() {
	}

	public Accessgroupldapgroups(int id, Ldapgroups ldapgroups, Rargroup rargroup) {
		this.id = id;
		this.ldapgroups = ldapgroups;
		this.rargroup = rargroup;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ldapgroup", nullable = false)
	public Ldapgroups getLdapgroups() {
		return this.ldapgroups;
	}

	public void setLdapgroups(Ldapgroups ldapgroups) {
		this.ldapgroups = ldapgroups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rargroup", nullable = false)
	public Rargroup getRargroup() {
		return this.rargroup;
	}

	public void setRargroup(Rargroup rargroup) {
		this.rargroup = rargroup;
	}

}
