package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Accessgroupldaporganizationunits generated by hbm2java
 */
@Entity
@Table(name = "accessgroupldaporganizationunits", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"rargroup", "ldap_ou_dn" }))
public class Accessgroupldaporganizationunits implements java.io.Serializable {

	private int id;
	private Ldaporganizationunits ldaporganizationunits;
	private Rargroup rargroup;

	public Accessgroupldaporganizationunits() {
	}

	public Accessgroupldaporganizationunits(int id, Ldaporganizationunits ldaporganizationunits, Rargroup rargroup) {
		this.id = id;
		this.ldaporganizationunits = ldaporganizationunits;
		this.rargroup = rargroup;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ldap_ou_dn", nullable = false)
	public Ldaporganizationunits getLdaporganizationunits() {
		return this.ldaporganizationunits;
	}

	public void setLdaporganizationunits(Ldaporganizationunits ldaporganizationunits) {
		this.ldaporganizationunits = ldaporganizationunits;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rargroup", nullable = false)
	public Rargroup getRargroup() {
		return this.rargroup;
	}

	public void setRargroup(Rargroup rargroup) {
		this.rargroup = rargroup;
	}

}
