package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Adminusersites generated by hbm2java
 */
@Entity
@Table(name = "adminusersites", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "siteid",
		"username" }))
public class Adminusersites implements java.io.Serializable {

	private int id;
	private Adminusers adminusers;
	private Sites sites;

	public Adminusersites() {
	}

	public Adminusersites(int id, Adminusers adminusers, Sites sites) {
		this.id = id;
		this.adminusers = adminusers;
		this.sites = sites;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Adminusers getAdminusers() {
		return this.adminusers;
	}

	public void setAdminusers(Adminusers adminusers) {
		this.adminusers = adminusers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "siteid", nullable = false)
	public Sites getSites() {
		return this.sites;
	}

	public void setSites(Sites sites) {
		this.sites = sites;
	}

}
