package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Adminusers generated by hbm2java
 */
@Entity
@Table(name = "adminusers", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Adminusers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String username;
	private String firstname;
	private String lastname;
	private String password;
	private Long securitymask;
	private String tc;
	private String rbLanguage;
	private Integer viewPageSize;
	private String securitylevel;
	private String userid;
	private Long usnchanged;
	private Set<Adminusersites> adminusersiteses = new HashSet<Adminusersites>(0);
	private Set<Busadmins> busadminses = new HashSet<Busadmins>(0);

	public Adminusers() {
	}

	public Adminusers(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public Adminusers(int id, String username, String firstname, String lastname, String password, Long securitymask,
			String tc, String rbLanguage, Integer viewPageSize, String securitylevel, String userid, Long usnchanged,
			Set<Adminusersites> adminusersiteses, Set<Busadmins> busadminses) {
		this.id = id;
		this.username = username;
		this.firstname = firstname;
		this.lastname = lastname;
		this.password = password;
		this.securitymask = securitymask;
		this.tc = tc;
		this.rbLanguage = rbLanguage;
		this.viewPageSize = viewPageSize;
		this.securitylevel = securitylevel;
		this.userid = userid;
		this.usnchanged = usnchanged;
		this.adminusersiteses = adminusersiteses;
		this.busadminses = busadminses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "password", nullable = false, length = 300)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "securitymask")
	public Long getSecuritymask() {
		return this.securitymask;
	}

	public void setSecuritymask(Long securitymask) {
		this.securitymask = securitymask;
	}

	@Column(name = "tc", length = 20)
	public String getTc() {
		return this.tc;
	}

	public void setTc(String tc) {
		this.tc = tc;
	}

	@Column(name = "rb_language", length = 10)
	public String getRbLanguage() {
		return this.rbLanguage;
	}

	public void setRbLanguage(String rbLanguage) {
		this.rbLanguage = rbLanguage;
	}

	@Column(name = "view_page_size")
	public Integer getViewPageSize() {
		return this.viewPageSize;
	}

	public void setViewPageSize(Integer viewPageSize) {
		this.viewPageSize = viewPageSize;
	}

	@Column(name = "securitylevel", length = 100)
	public String getSecuritylevel() {
		return this.securitylevel;
	}

	public void setSecuritylevel(String securitylevel) {
		this.securitylevel = securitylevel;
	}

	@Column(name = "userid", length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adminusers")
	public Set<Adminusersites> getAdminusersiteses() {
		return this.adminusersiteses;
	}

	public void setAdminusersiteses(Set<Adminusersites> adminusersiteses) {
		this.adminusersiteses = adminusersiteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adminusers")
	public Set<Busadmins> getBusadminses() {
		return this.busadminses;
	}

	public void setBusadminses(Set<Busadmins> busadminses) {
		this.busadminses = busadminses;
	}

}
