package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Alarmlogs generated by hbm2java
 */
@Entity
@Table(name = "alarmlogs", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "log_id",
		"serverid" }))
public class Alarmlogs implements java.io.Serializable {

	private long logId;
	private String serverid;
	private Date logtime;
	private String activitytype;
	private String deviceid;
	private String devicename;
	private String portname;
	private String info;
	private String origname;
	private String result;
	private String snapshot;
	private String severity;
	private String level;
	private Integer logtype;
	private String suiteid;
	private String userid;
	private String lastname;
	private String firstname;
	private String cardnumber;
	private Boolean sent;
	private Long instructionId;
	private Boolean ackrequired;
	private String devicetype;
	private String iocontrol;
	private int siteid;
	private String zoneid;
	private Integer portnumber;
	private String ackuser;
	private String acknotes;
	private Date acktime;
	private Date cleartime;
	private String clearuser;
	private String clearnotes;
	private String zonename;

	public Alarmlogs() {
	}

	public Alarmlogs(long logId, String serverid, Date logtime, int siteid) {
		this.logId = logId;
		this.serverid = serverid;
		this.logtime = logtime;
		this.siteid = siteid;
	}

	public Alarmlogs(long logId, String serverid, Date logtime, String activitytype, String deviceid, String devicename,
			String portname, String info, String origname, String result, String snapshot, String severity,
			String level, Integer logtype, String suiteid, String userid, String lastname, String firstname,
			String cardnumber, Boolean sent, Long instructionId, Boolean ackrequired, String devicetype,
			String iocontrol, int siteid, String zoneid, Integer portnumber, String ackuser, String acknotes,
			Date acktime, Date cleartime, String clearuser, String clearnotes, String zonename) {
		this.logId = logId;
		this.serverid = serverid;
		this.logtime = logtime;
		this.activitytype = activitytype;
		this.deviceid = deviceid;
		this.devicename = devicename;
		this.portname = portname;
		this.info = info;
		this.origname = origname;
		this.result = result;
		this.snapshot = snapshot;
		this.severity = severity;
		this.level = level;
		this.logtype = logtype;
		this.suiteid = suiteid;
		this.userid = userid;
		this.lastname = lastname;
		this.firstname = firstname;
		this.cardnumber = cardnumber;
		this.sent = sent;
		this.instructionId = instructionId;
		this.ackrequired = ackrequired;
		this.devicetype = devicetype;
		this.iocontrol = iocontrol;
		this.siteid = siteid;
		this.zoneid = zoneid;
		this.portnumber = portnumber;
		this.ackuser = ackuser;
		this.acknotes = acknotes;
		this.acktime = acktime;
		this.cleartime = cleartime;
		this.clearuser = clearuser;
		this.clearnotes = clearnotes;
		this.zonename = zonename;
	}

	@Id

	@Column(name = "log_id", unique = true, nullable = false)
	public long getLogId() {
		return this.logId;
	}

	public void setLogId(long logId) {
		this.logId = logId;
	}

	@Column(name = "serverid", nullable = false, length = 50)
	public String getServerid() {
		return this.serverid;
	}

	public void setServerid(String serverid) {
		this.serverid = serverid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logtime", nullable = false, length = 29)
	public Date getLogtime() {
		return this.logtime;
	}

	public void setLogtime(Date logtime) {
		this.logtime = logtime;
	}

	@Column(name = "activitytype", length = 20)
	public String getActivitytype() {
		return this.activitytype;
	}

	public void setActivitytype(String activitytype) {
		this.activitytype = activitytype;
	}

	@Column(name = "deviceid", length = 100)
	public String getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	@Column(name = "devicename", length = 100)
	public String getDevicename() {
		return this.devicename;
	}

	public void setDevicename(String devicename) {
		this.devicename = devicename;
	}

	@Column(name = "portname", length = 50)
	public String getPortname() {
		return this.portname;
	}

	public void setPortname(String portname) {
		this.portname = portname;
	}

	@Column(name = "info", length = 400)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "origname", length = 50)
	public String getOrigname() {
		return this.origname;
	}

	public void setOrigname(String origname) {
		this.origname = origname;
	}

	@Column(name = "result", length = 50)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "snapshot", length = 50)
	public String getSnapshot() {
		return this.snapshot;
	}

	public void setSnapshot(String snapshot) {
		this.snapshot = snapshot;
	}

	@Column(name = "severity", length = 50)
	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	@Column(name = "level", length = 20)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "logtype")
	public Integer getLogtype() {
		return this.logtype;
	}

	public void setLogtype(Integer logtype) {
		this.logtype = logtype;
	}

	@Column(name = "suiteid", length = 50)
	public String getSuiteid() {
		return this.suiteid;
	}

	public void setSuiteid(String suiteid) {
		this.suiteid = suiteid;
	}

	@Column(name = "userid", length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "cardnumber", length = 100)
	public String getCardnumber() {
		return this.cardnumber;
	}

	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}

	@Column(name = "sent")
	public Boolean getSent() {
		return this.sent;
	}

	public void setSent(Boolean sent) {
		this.sent = sent;
	}

	@Column(name = "instruction_id")
	public Long getInstructionId() {
		return this.instructionId;
	}

	public void setInstructionId(Long instructionId) {
		this.instructionId = instructionId;
	}

	@Column(name = "ackrequired")
	public Boolean getAckrequired() {
		return this.ackrequired;
	}

	public void setAckrequired(Boolean ackrequired) {
		this.ackrequired = ackrequired;
	}

	@Column(name = "devicetype", length = 50)
	public String getDevicetype() {
		return this.devicetype;
	}

	public void setDevicetype(String devicetype) {
		this.devicetype = devicetype;
	}

	@Column(name = "iocontrol", length = 2)
	public String getIocontrol() {
		return this.iocontrol;
	}

	public void setIocontrol(String iocontrol) {
		this.iocontrol = iocontrol;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	@Column(name = "zoneid", length = 200)
	public String getZoneid() {
		return this.zoneid;
	}

	public void setZoneid(String zoneid) {
		this.zoneid = zoneid;
	}

	@Column(name = "portnumber")
	public Integer getPortnumber() {
		return this.portnumber;
	}

	public void setPortnumber(Integer portnumber) {
		this.portnumber = portnumber;
	}

	@Column(name = "ackuser", length = 50)
	public String getAckuser() {
		return this.ackuser;
	}

	public void setAckuser(String ackuser) {
		this.ackuser = ackuser;
	}

	@Column(name = "acknotes", length = 1024)
	public String getAcknotes() {
		return this.acknotes;
	}

	public void setAcknotes(String acknotes) {
		this.acknotes = acknotes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acktime", length = 35)
	public Date getAcktime() {
		return this.acktime;
	}

	public void setAcktime(Date acktime) {
		this.acktime = acktime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cleartime", length = 35)
	public Date getCleartime() {
		return this.cleartime;
	}

	public void setCleartime(Date cleartime) {
		this.cleartime = cleartime;
	}

	@Column(name = "clearuser", length = 50)
	public String getClearuser() {
		return this.clearuser;
	}

	public void setClearuser(String clearuser) {
		this.clearuser = clearuser;
	}

	@Column(name = "clearnotes", length = 1024)
	public String getClearnotes() {
		return this.clearnotes;
	}

	public void setClearnotes(String clearnotes) {
		this.clearnotes = clearnotes;
	}

	@Column(name = "zonename")
	public String getZonename() {
		return this.zonename;
	}

	public void setZonename(String zonename) {
		this.zonename = zonename;
	}

}
