package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Busadmins generated by hbm2java
 */
@Entity
@Table(name = "busadmins", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "username",
		"busname" }))
public class Busadmins implements java.io.Serializable {

	private long id;
	private Adminusers adminusers;
	private String busname;

	public Busadmins() {
	}

	public Busadmins(long id, Adminusers adminusers, String busname) {
		this.id = id;
		this.adminusers = adminusers;
		this.busname = busname;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Adminusers getAdminusers() {
		return this.adminusers;
	}

	public void setAdminusers(Adminusers adminusers) {
		this.adminusers = adminusers;
	}

	@Column(name = "busname", nullable = false, length = 80)
	public String getBusname() {
		return this.busname;
	}

	public void setBusname(String busname) {
		this.busname = busname;
	}

}
