package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Busflooraccess generated by hbm2java
 */
@Entity
@Table(name = "busflooraccess", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "busname",
		"fargroup" }))
public class Busflooraccess implements java.io.Serializable {

	private long id;
	private Business business;
	private Fargroup fargroup;

	public Busflooraccess() {
	}

	public Busflooraccess(long id, Business business, Fargroup fargroup) {
		this.id = id;
		this.business = business;
		this.fargroup = fargroup;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "busname", nullable = false)
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fargroup", nullable = false)
	public Fargroup getFargroup() {
		return this.fargroup;
	}

	public void setFargroup(Fargroup fargroup) {
		this.fargroup = fargroup;
	}

}
