package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cardformat generated by hbm2java
 */
@Entity
@Table(name = "cardformat", schema = "public")
public class Cardformat implements java.io.Serializable {

	private int formatId;
	private Integer bitLength;
	private String formatDesc;
	private Integer formatType;
	private String formatDef;
	private Integer sortOrder;
	private Boolean formatDefault;
	private Long usnchanged;
	private boolean formatEnabled;
	private String parityMask;
	private Boolean parityCheck;

	public Cardformat() {
	}

	public Cardformat(int formatId, boolean formatEnabled) {
		this.formatId = formatId;
		this.formatEnabled = formatEnabled;
	}

	public Cardformat(int formatId, Integer bitLength, String formatDesc, Integer formatType, String formatDef,
			Integer sortOrder, Boolean formatDefault, Long usnchanged, boolean formatEnabled, String parityMask,
			Boolean parityCheck) {
		this.formatId = formatId;
		this.bitLength = bitLength;
		this.formatDesc = formatDesc;
		this.formatType = formatType;
		this.formatDef = formatDef;
		this.sortOrder = sortOrder;
		this.formatDefault = formatDefault;
		this.usnchanged = usnchanged;
		this.formatEnabled = formatEnabled;
		this.parityMask = parityMask;
		this.parityCheck = parityCheck;
	}

	@Id

	@Column(name = "format_id", unique = true, nullable = false)
	public int getFormatId() {
		return this.formatId;
	}

	public void setFormatId(int formatId) {
		this.formatId = formatId;
	}

	@Column(name = "bit_length")
	public Integer getBitLength() {
		return this.bitLength;
	}

	public void setBitLength(Integer bitLength) {
		this.bitLength = bitLength;
	}

	@Column(name = "format_desc", length = 100)
	public String getFormatDesc() {
		return this.formatDesc;
	}

	public void setFormatDesc(String formatDesc) {
		this.formatDesc = formatDesc;
	}

	@Column(name = "format_type")
	public Integer getFormatType() {
		return this.formatType;
	}

	public void setFormatType(Integer formatType) {
		this.formatType = formatType;
	}

	@Column(name = "format_def", length = 200)
	public String getFormatDef() {
		return this.formatDef;
	}

	public void setFormatDef(String formatDef) {
		this.formatDef = formatDef;
	}

	@Column(name = "sort_order")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "format_default")
	public Boolean getFormatDefault() {
		return this.formatDefault;
	}

	public void setFormatDefault(Boolean formatDefault) {
		this.formatDefault = formatDefault;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@Column(name = "format_enabled", nullable = false)
	public boolean isFormatEnabled() {
		return this.formatEnabled;
	}

	public void setFormatEnabled(boolean formatEnabled) {
		this.formatEnabled = formatEnabled;
	}

	@Column(name = "parity_mask", length = 250)
	public String getParityMask() {
		return this.parityMask;
	}

	public void setParityMask(String parityMask) {
		this.parityMask = parityMask;
	}

	@Column(name = "parity_check")
	public Boolean getParityCheck() {
		return this.parityCheck;
	}

	public void setParityCheck(Boolean parityCheck) {
		this.parityCheck = parityCheck;
	}

}
