package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * CardTemplates generated by hbm2java
 */
@Entity
@Table(name = "card_templates", schema = "public")
public class CardTemplates implements java.io.Serializable {

	private long id;
	private String version;
	private Double cardHeight;
	private Double cardWidth;
	private String content;
	private Date createdAt;
	private String description;
	private Integer height;
	private Boolean inUse;
	private String name;
	private Integer printerDpi;
	private Integer scope;
	private String type;
	private Date updatedAt;
	private Integer width;
	private Integer siteid;

	public CardTemplates() {
	}

	public CardTemplates(long id) {
		this.id = id;
	}

	public CardTemplates(long id, Double cardHeight, Double cardWidth, String content, Date createdAt,
			String description, Integer height, Boolean inUse, String name, Integer printerDpi, Integer scope,
			String type, Date updatedAt, Integer width, Integer siteid) {
		this.id = id;
		this.cardHeight = cardHeight;
		this.cardWidth = cardWidth;
		this.content = content;
		this.createdAt = createdAt;
		this.description = description;
		this.height = height;
		this.inUse = inUse;
		this.name = name;
		this.printerDpi = printerDpi;
		this.scope = scope;
		this.type = type;
		this.updatedAt = updatedAt;
		this.width = width;
		this.siteid = siteid;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "card_height", precision = 17, scale = 17)
	public Double getCardHeight() {
		return this.cardHeight;
	}

	public void setCardHeight(Double cardHeight) {
		this.cardHeight = cardHeight;
	}

	@Column(name = "card_width", precision = 17, scale = 17)
	public Double getCardWidth() {
		return this.cardWidth;
	}

	public void setCardWidth(Double cardWidth) {
		this.cardWidth = cardWidth;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "in_use")
	public Boolean getInUse() {
		return this.inUse;
	}

	public void setInUse(Boolean inUse) {
		this.inUse = inUse;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "printer_dpi")
	public Integer getPrinterDpi() {
		return this.printerDpi;
	}

	public void setPrinterDpi(Integer printerDpi) {
		this.printerDpi = printerDpi;
	}

	@Column(name = "scope")
	public Integer getScope() {
		return this.scope;
	}

	public void setScope(Integer scope) {
		this.scope = scope;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "width")
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "siteid")
	public Integer getSiteid() {
		return this.siteid;
	}

	public void setSiteid(Integer siteid) {
		this.siteid = siteid;
	}

}
