package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Carddata generated by hbm2java
 */
@Entity
@Table(name = "carddata", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "carddata"))
public class Carddata implements java.io.Serializable {

	private long id;
	private Users users;
	private String carddata;
	private String type;
	private Date createdAt;
	private Date updatedAt;
	private Boolean disabled;

	public Carddata() {
	}

	public Carddata(long id, Users users, String carddata, String type, Date createdAt, Date updatedAt) {
		this.id = id;
		this.users = users;
		this.carddata = carddata;
		this.type = type;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Carddata(long id, Users users, String carddata, String type, Date createdAt, Date updatedAt,
			Boolean disabled) {
		this.id = id;
		this.users = users;
		this.carddata = carddata;
		this.type = type;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.disabled = disabled;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "carddata", unique = true, nullable = false, length = 100)
	public String getCarddata() {
		return this.carddata;
	}

	public void setCarddata(String carddata) {
		this.carddata = carddata;
	}

	@Column(name = "type", nullable = false, length = 5)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "disabled")
	public Boolean getDisabled() {
		return this.disabled;
	}

	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}

}
