package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Caschedules generated by hbm2java
 */
@Entity
@Table(name = "caschedules", schema = "public")
public class Caschedules implements java.io.Serializable {

	private String cascheduleid;
	private Schedule schedule;
	private Zones zones;
	private int onaction;
	private Integer offaction;
	private String description;
	private Integer alertlevels;

	public Caschedules() {
	}

	public Caschedules(String cascheduleid, Schedule schedule, Zones zones, int onaction) {
		this.cascheduleid = cascheduleid;
		this.schedule = schedule;
		this.zones = zones;
		this.onaction = onaction;
	}

	public Caschedules(String cascheduleid, Schedule schedule, Zones zones, int onaction, Integer offaction,
			String description, Integer alertlevels) {
		this.cascheduleid = cascheduleid;
		this.schedule = schedule;
		this.zones = zones;
		this.onaction = onaction;
		this.offaction = offaction;
		this.description = description;
		this.alertlevels = alertlevels;
	}

	@Id

	@Column(name = "cascheduleid", unique = true, nullable = false, length = 50)
	public String getCascheduleid() {
		return this.cascheduleid;
	}

	public void setCascheduleid(String cascheduleid) {
		this.cascheduleid = cascheduleid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scheduleid", nullable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caid", nullable = false)
	public Zones getZones() {
		return this.zones;
	}

	public void setZones(Zones zones) {
		this.zones = zones;
	}

	@Column(name = "onaction", nullable = false)
	public int getOnaction() {
		return this.onaction;
	}

	public void setOnaction(int onaction) {
		this.onaction = onaction;
	}

	@Column(name = "offaction")
	public Integer getOffaction() {
		return this.offaction;
	}

	public void setOffaction(Integer offaction) {
		this.offaction = offaction;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "alertlevels")
	public Integer getAlertlevels() {
		return this.alertlevels;
	}

	public void setAlertlevels(Integer alertlevels) {
		this.alertlevels = alertlevels;
	}

}
