package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Certificatepolicies generated by hbm2java
 */
@Entity
@Table(name = "certificatepolicies", schema = "public")
public class Certificatepolicies implements java.io.Serializable {

	private int id;
	private int oidType;
	private String oid;
	private String description;

	public Certificatepolicies() {
	}

	public Certificatepolicies(int id, int oidType, String oid, String description) {
		this.id = id;
		this.oidType = oidType;
		this.oid = oid;
		this.description = description;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "oid_type", nullable = false)
	public int getOidType() {
		return this.oidType;
	}

	public void setOidType(int oidType) {
		this.oidType = oidType;
	}

	@Column(name = "oid", nullable = false, length = 50)
	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
