package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Credentials generated by hbm2java
 */
@Entity
@Table(name = "credentials", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "fascn_hex"))
public class Credentials implements java.io.Serializable {

	private long id;
	private Users users;
	private String fascnHex;
	private String credentialType;
	private String fascnAgencyCode;
	private String fascnSystemCode;
	private String fascnCredentialNumber;
	private Character fascnCredentialSeries;
	private Character fascnCredentialIssue;
	private String fascnPersonalId;
	private Character fascnOrgCategory;
	private String fascnOrgId;
	private Character fascnPersonOrgAssociation;
	private String status;
	private Date expirationDate;
	private String guid;
	private String cardAuthKey;
	private Set<Certificates> certificateses = new HashSet<Certificates>(0);

	public Credentials() {
	}

	public Credentials(long id, String status) {
		this.id = id;
		this.status = status;
	}

	public Credentials(long id, Users users, String fascnHex, String credentialType, String fascnAgencyCode,
			String fascnSystemCode, String fascnCredentialNumber, Character fascnCredentialSeries,
			Character fascnCredentialIssue, String fascnPersonalId, Character fascnOrgCategory, String fascnOrgId,
			Character fascnPersonOrgAssociation, String status, Date expirationDate, String guid, String cardAuthKey,
			Set<Certificates> certificateses) {
		this.id = id;
		this.users = users;
		this.fascnHex = fascnHex;
		this.credentialType = credentialType;
		this.fascnAgencyCode = fascnAgencyCode;
		this.fascnSystemCode = fascnSystemCode;
		this.fascnCredentialNumber = fascnCredentialNumber;
		this.fascnCredentialSeries = fascnCredentialSeries;
		this.fascnCredentialIssue = fascnCredentialIssue;
		this.fascnPersonalId = fascnPersonalId;
		this.fascnOrgCategory = fascnOrgCategory;
		this.fascnOrgId = fascnOrgId;
		this.fascnPersonOrgAssociation = fascnPersonOrgAssociation;
		this.status = status;
		this.expirationDate = expirationDate;
		this.guid = guid;
		this.cardAuthKey = cardAuthKey;
		this.certificateses = certificateses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "fascn_hex", unique = true, length = 50)
	public String getFascnHex() {
		return this.fascnHex;
	}

	public void setFascnHex(String fascnHex) {
		this.fascnHex = fascnHex;
	}

	@Column(name = "credential_type", length = 10)
	public String getCredentialType() {
		return this.credentialType;
	}

	public void setCredentialType(String credentialType) {
		this.credentialType = credentialType;
	}

	@Column(name = "fascn_agency_code", length = 4)
	public String getFascnAgencyCode() {
		return this.fascnAgencyCode;
	}

	public void setFascnAgencyCode(String fascnAgencyCode) {
		this.fascnAgencyCode = fascnAgencyCode;
	}

	@Column(name = "fascn_system_code", length = 4)
	public String getFascnSystemCode() {
		return this.fascnSystemCode;
	}

	public void setFascnSystemCode(String fascnSystemCode) {
		this.fascnSystemCode = fascnSystemCode;
	}

	@Column(name = "fascn_credential_number", length = 6)
	public String getFascnCredentialNumber() {
		return this.fascnCredentialNumber;
	}

	public void setFascnCredentialNumber(String fascnCredentialNumber) {
		this.fascnCredentialNumber = fascnCredentialNumber;
	}

	@Column(name = "fascn_credential_series", length = 1)
	public Character getFascnCredentialSeries() {
		return this.fascnCredentialSeries;
	}

	public void setFascnCredentialSeries(Character fascnCredentialSeries) {
		this.fascnCredentialSeries = fascnCredentialSeries;
	}

	@Column(name = "fascn_credential_issue", length = 1)
	public Character getFascnCredentialIssue() {
		return this.fascnCredentialIssue;
	}

	public void setFascnCredentialIssue(Character fascnCredentialIssue) {
		this.fascnCredentialIssue = fascnCredentialIssue;
	}

	@Column(name = "fascn_personal_id", length = 10)
	public String getFascnPersonalId() {
		return this.fascnPersonalId;
	}

	public void setFascnPersonalId(String fascnPersonalId) {
		this.fascnPersonalId = fascnPersonalId;
	}

	@Column(name = "fascn_org_category", length = 1)
	public Character getFascnOrgCategory() {
		return this.fascnOrgCategory;
	}

	public void setFascnOrgCategory(Character fascnOrgCategory) {
		this.fascnOrgCategory = fascnOrgCategory;
	}

	@Column(name = "fascn_org_id", length = 4)
	public String getFascnOrgId() {
		return this.fascnOrgId;
	}

	public void setFascnOrgId(String fascnOrgId) {
		this.fascnOrgId = fascnOrgId;
	}

	@Column(name = "fascn_person_org_association", length = 1)
	public Character getFascnPersonOrgAssociation() {
		return this.fascnPersonOrgAssociation;
	}

	public void setFascnPersonOrgAssociation(Character fascnPersonOrgAssociation) {
		this.fascnPersonOrgAssociation = fascnPersonOrgAssociation;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", length = 13)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "guid")
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "card_auth_key")
	public String getCardAuthKey() {
		return this.cardAuthKey;
	}

	public void setCardAuthKey(String cardAuthKey) {
		this.cardAuthKey = cardAuthKey;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "credentials")
	public Set<Certificates> getCertificateses() {
		return this.certificateses;
	}

	public void setCertificateses(Set<Certificates> certificateses) {
		this.certificateses = certificateses;
	}

}
