package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customfields generated by hbm2java
 */
@Entity
@Table(name = "customfields", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "label"))
public class Customfields implements java.io.Serializable {

	private long id;
	private String label;
	private String valueOptions;
	private Integer sortOrder;

	public Customfields() {
	}

	public Customfields(long id, String label) {
		this.id = id;
		this.label = label;
	}

	public Customfields(long id, String label, String valueOptions, Integer sortOrder) {
		this.id = id;
		this.label = label;
		this.valueOptions = valueOptions;
		this.sortOrder = sortOrder;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "label", unique = true, nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "value_options")
	public String getValueOptions() {
		return this.valueOptions;
	}

	public void setValueOptions(String valueOptions) {
		this.valueOptions = valueOptions;
	}

	@Column(name = "sort_order")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
