package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customfielditems generated by hbm2java
 */
@Entity
@Table(name = "customfielditems", schema = "public")
public class Customfielditems implements java.io.Serializable {

	private long id;
	private String content;
	private long customfieldId;
	private String userId;

	public Customfielditems() {
	}

	public Customfielditems(long id, long customfieldId) {
		this.id = id;
		this.customfieldId = customfieldId;
	}

	public Customfielditems(long id, String content, long customfieldId, String userId) {
		this.id = id;
		this.content = content;
		this.customfieldId = customfieldId;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "customfield_id", nullable = false)
	public long getCustomfieldId() {
		return this.customfieldId;
	}

	public void setCustomfieldId(long customfieldId) {
		this.customfieldId = customfieldId;
	}

	@Column(name = "user_id", length = 200)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
