package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DblogUsernotes generated by hbm2java
 */
@Entity
@Table(name = "dblog_usernotes", schema = "public")
public class DblogUsernotes implements java.io.Serializable {

	private int dblogId;
	private String userid;
	private String usernote;

	public DblogUsernotes() {
	}

	public DblogUsernotes(int dblogId, String userid) {
		this.dblogId = dblogId;
		this.userid = userid;
	}

	public DblogUsernotes(int dblogId, String userid, String usernote) {
		this.dblogId = dblogId;
		this.userid = userid;
		this.usernote = usernote;
	}

	@Id

	@Column(name = "dblog_id", unique = true, nullable = false)
	public int getDblogId() {
		return this.dblogId;
	}

	public void setDblogId(int dblogId) {
		this.dblogId = dblogId;
	}

	@Column(name = "userid", nullable = false, length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "usernote", length = 512)
	public String getUsernote() {
		return this.usernote;
	}

	public void setUsernote(String usernote) {
		this.usernote = usernote;
	}

}
