package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DblogUseraccessgroups generated by hbm2java
 */
@Entity
@Table(name = "dblog_useraccessgroups", schema = "public")
public class DblogUseraccessgroups implements java.io.Serializable {

	private int dblogId;
	private String userid;
	private String rargroup;
	private Boolean alwayson;
	private Date startdate;
	private Date enddate;

	public DblogUseraccessgroups() {
	}

	public DblogUseraccessgroups(int dblogId) {
		this.dblogId = dblogId;
	}

	public DblogUseraccessgroups(int dblogId, String userid, String rargroup, Boolean alwayson, Date startdate,
			Date enddate) {
		this.dblogId = dblogId;
		this.userid = userid;
		this.rargroup = rargroup;
		this.alwayson = alwayson;
		this.startdate = startdate;
		this.enddate = enddate;
	}

	@Id

	@Column(name = "dblog_id", unique = true, nullable = false)
	public int getDblogId() {
		return this.dblogId;
	}

	public void setDblogId(int dblogId) {
		this.dblogId = dblogId;
	}

	@Column(name = "userid", length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "rargroup", length = 100)
	public String getRargroup() {
		return this.rargroup;
	}

	public void setRargroup(String rargroup) {
		this.rargroup = rargroup;
	}

	@Column(name = "alwayson")
	public Boolean getAlwayson() {
		return this.alwayson;
	}

	public void setAlwayson(Boolean alwayson) {
		this.alwayson = alwayson;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdate", length = 29)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enddate", length = 29)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

}
