package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DblogCarddata generated by hbm2java
 */
@Entity
@Table(name = "dblog_carddata", schema = "public")
public class DblogCarddata implements java.io.Serializable {

	private int dblogId;
	private String userid;
	private String carddata;
	private String type;
	private Date createdAt;
	private Date updatedAt;
	private Boolean disabled;

	public DblogCarddata() {
	}

	public DblogCarddata(int dblogId, String userid, String carddata, String type, Date createdAt, Date updatedAt) {
		this.dblogId = dblogId;
		this.userid = userid;
		this.carddata = carddata;
		this.type = type;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public DblogCarddata(int dblogId, String userid, String carddata, String type, Date createdAt, Date updatedAt,
			Boolean disabled) {
		this.dblogId = dblogId;
		this.userid = userid;
		this.carddata = carddata;
		this.type = type;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.disabled = disabled;
	}

	@Id

	@Column(name = "dblog_id", unique = true, nullable = false)
	public int getDblogId() {
		return this.dblogId;
	}

	public void setDblogId(int dblogId) {
		this.dblogId = dblogId;
	}

	@Column(name = "userid", nullable = false, length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "carddata", nullable = false, length = 100)
	public String getCarddata() {
		return this.carddata;
	}

	public void setCarddata(String carddata) {
		this.carddata = carddata;
	}

	@Column(name = "type", nullable = false, length = 5)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 35)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 35)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "disabled")
	public Boolean getDisabled() {
		return this.disabled;
	}

	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}

}
