package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DblogCertificates generated by hbm2java
 */
@Entity
@Table(name = "dblog_certificates", schema = "public")
public class DblogCertificates implements java.io.Serializable {

	private int dblogId;
	private long id;
	private long credentialId;
	private int type;
	private Date notBefore;
	private Date notAfter;
	private Date validatedAt;
	private int status;
	private String content;
	private String serialnumber;
	private String issuername;
	private String crlHttp;
	private String crlHttps;
	private String crlFtp;
	private String crlLdap;
	private Date crlNextupdate;

	public DblogCertificates() {
	}

	public DblogCertificates(int dblogId, long id, long credentialId, int type, Date notBefore, Date notAfter,
			int status, String content) {
		this.dblogId = dblogId;
		this.id = id;
		this.credentialId = credentialId;
		this.type = type;
		this.notBefore = notBefore;
		this.notAfter = notAfter;
		this.status = status;
		this.content = content;
	}

	public DblogCertificates(int dblogId, long id, long credentialId, int type, Date notBefore, Date notAfter,
			Date validatedAt, int status, String content, String serialnumber, String issuername, String crlHttp,
			String crlHttps, String crlFtp, String crlLdap, Date crlNextupdate) {
		this.dblogId = dblogId;
		this.id = id;
		this.credentialId = credentialId;
		this.type = type;
		this.notBefore = notBefore;
		this.notAfter = notAfter;
		this.validatedAt = validatedAt;
		this.status = status;
		this.content = content;
		this.serialnumber = serialnumber;
		this.issuername = issuername;
		this.crlHttp = crlHttp;
		this.crlHttps = crlHttps;
		this.crlFtp = crlFtp;
		this.crlLdap = crlLdap;
		this.crlNextupdate = crlNextupdate;
	}

	@Id

	@Column(name = "dblog_id", unique = true, nullable = false)
	public int getDblogId() {
		return this.dblogId;
	}

	public void setDblogId(int dblogId) {
		this.dblogId = dblogId;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "credential_id", nullable = false)
	public long getCredentialId() {
		return this.credentialId;
	}

	public void setCredentialId(long credentialId) {
		this.credentialId = credentialId;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "not_before", nullable = false, length = 29)
	public Date getNotBefore() {
		return this.notBefore;
	}

	public void setNotBefore(Date notBefore) {
		this.notBefore = notBefore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "not_after", nullable = false, length = 29)
	public Date getNotAfter() {
		return this.notAfter;
	}

	public void setNotAfter(Date notAfter) {
		this.notAfter = notAfter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "validated_at", length = 29)
	public Date getValidatedAt() {
		return this.validatedAt;
	}

	public void setValidatedAt(Date validatedAt) {
		this.validatedAt = validatedAt;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "serialnumber", length = 300)
	public String getSerialnumber() {
		return this.serialnumber;
	}

	public void setSerialnumber(String serialnumber) {
		this.serialnumber = serialnumber;
	}

	@Column(name = "issuername", length = 300)
	public String getIssuername() {
		return this.issuername;
	}

	public void setIssuername(String issuername) {
		this.issuername = issuername;
	}

	@Column(name = "crl_http", length = 300)
	public String getCrlHttp() {
		return this.crlHttp;
	}

	public void setCrlHttp(String crlHttp) {
		this.crlHttp = crlHttp;
	}

	@Column(name = "crl_https", length = 300)
	public String getCrlHttps() {
		return this.crlHttps;
	}

	public void setCrlHttps(String crlHttps) {
		this.crlHttps = crlHttps;
	}

	@Column(name = "crl_ftp", length = 300)
	public String getCrlFtp() {
		return this.crlFtp;
	}

	public void setCrlFtp(String crlFtp) {
		this.crlFtp = crlFtp;
	}

	@Column(name = "crl_ldap", length = 300)
	public String getCrlLdap() {
		return this.crlLdap;
	}

	public void setCrlLdap(String crlLdap) {
		this.crlLdap = crlLdap;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crl_nextupdate", length = 29)
	public Date getCrlNextupdate() {
		return this.crlNextupdate;
	}

	public void setCrlNextupdate(Date crlNextupdate) {
		this.crlNextupdate = crlNextupdate;
	}

}
