package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DblogQueue generated by hbm2java
 */
@Entity
@Table(name = "dblog_queue", schema = "public")
public class DblogQueue implements java.io.Serializable {

	private int dblogId;
	private int dblogType;
	private String userid;
	private Date createdAt;
	private Date completedAt;
	private int resultCode;
	private String resultMsg;

	public DblogQueue() {
	}

	public DblogQueue(int dblogId, int dblogType, String userid, Date createdAt, int resultCode, String resultMsg) {
		this.dblogId = dblogId;
		this.dblogType = dblogType;
		this.userid = userid;
		this.createdAt = createdAt;
		this.resultCode = resultCode;
		this.resultMsg = resultMsg;
	}

	public DblogQueue(int dblogId, int dblogType, String userid, Date createdAt, Date completedAt, int resultCode,
			String resultMsg) {
		this.dblogId = dblogId;
		this.dblogType = dblogType;
		this.userid = userid;
		this.createdAt = createdAt;
		this.completedAt = completedAt;
		this.resultCode = resultCode;
		this.resultMsg = resultMsg;
	}

	@Id

	@Column(name = "dblog_id", unique = true, nullable = false)
	public int getDblogId() {
		return this.dblogId;
	}

	public void setDblogId(int dblogId) {
		this.dblogId = dblogId;
	}

	@Column(name = "dblog_type", nullable = false)
	public int getDblogType() {
		return this.dblogType;
	}

	public void setDblogType(int dblogType) {
		this.dblogType = dblogType;
	}

	@Column(name = "userid", nullable = false, length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "completed_at", length = 29)
	public Date getCompletedAt() {
		return this.completedAt;
	}

	public void setCompletedAt(Date completedAt) {
		this.completedAt = completedAt;
	}

	@Column(name = "result_code", nullable = false)
	public int getResultCode() {
		return this.resultCode;
	}

	public void setResultCode(int resultCode) {
		this.resultCode = resultCode;
	}

	@Column(name = "result_msg", nullable = false, length = 500)
	public String getResultMsg() {
		return this.resultMsg;
	}

	public void setResultMsg(String resultMsg) {
		this.resultMsg = resultMsg;
	}

}
