package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Devices generated by hbm2java
 */
@Entity
@Table(name = "devices", schema = "public")
public class Devices implements java.io.Serializable {

	private String serialnumber;
	private Systemports systemports;
	private Long type;
	private String description;
	private Long networkid;
	private String networkaddress;
	private Long state;
	private String mapstodevice;
	private Boolean senddevicealivemsg;
	private Long relayactivationperiod;
	private Long relaydelayperiod;
	private Boolean relaynormallyclosed;
	private Boolean pollfortagread;
	private Boolean sendtagoutoffieldmsg;
	private Long ledflashtime;
	private Long ledflashcolor;
	private Long buzzertime;
	private Boolean requiresconfigsync;
	private Integer mapstoport;
	private Integer securerelay;
	private Integer global;
	private String devicecn;
	private Long usnchanged;
	private int siteid;
	private Integer rs485PortType;
	private Set<Zonedevices> zonedeviceses = new HashSet<Zonedevices>(0);
	private Set<Deviceports> deviceportses = new HashSet<Deviceports>(0);

	public Devices() {
	}

	public Devices(String serialnumber, int siteid) {
		this.serialnumber = serialnumber;
		this.siteid = siteid;
	}

	public Devices(String serialnumber, Systemports systemports, Long type, String description, Long networkid,
			String networkaddress, Long state, String mapstodevice, Boolean senddevicealivemsg,
			Long relayactivationperiod, Long relaydelayperiod, Boolean relaynormallyclosed, Boolean pollfortagread,
			Boolean sendtagoutoffieldmsg, Long ledflashtime, Long ledflashcolor, Long buzzertime,
			Boolean requiresconfigsync, Integer mapstoport, Integer securerelay, Integer global, String devicecn,
			Long usnchanged, int siteid, Integer rs485PortType, Set<Zonedevices> zonedeviceses,
			Set<Deviceports> deviceportses) {
		this.serialnumber = serialnumber;
		this.systemports = systemports;
		this.type = type;
		this.description = description;
		this.networkid = networkid;
		this.networkaddress = networkaddress;
		this.state = state;
		this.mapstodevice = mapstodevice;
		this.senddevicealivemsg = senddevicealivemsg;
		this.relayactivationperiod = relayactivationperiod;
		this.relaydelayperiod = relaydelayperiod;
		this.relaynormallyclosed = relaynormallyclosed;
		this.pollfortagread = pollfortagread;
		this.sendtagoutoffieldmsg = sendtagoutoffieldmsg;
		this.ledflashtime = ledflashtime;
		this.ledflashcolor = ledflashcolor;
		this.buzzertime = buzzertime;
		this.requiresconfigsync = requiresconfigsync;
		this.mapstoport = mapstoport;
		this.securerelay = securerelay;
		this.global = global;
		this.devicecn = devicecn;
		this.usnchanged = usnchanged;
		this.siteid = siteid;
		this.rs485PortType = rs485PortType;
		this.zonedeviceses = zonedeviceses;
		this.deviceportses = deviceportses;
	}

	@Id

	@Column(name = "serialnumber", unique = true, nullable = false, length = 100)
	public String getSerialnumber() {
		return this.serialnumber;
	}

	public void setSerialnumber(String serialnumber) {
		this.serialnumber = serialnumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "systemportname")
	public Systemports getSystemports() {
		return this.systemports;
	}

	public void setSystemports(Systemports systemports) {
		this.systemports = systemports;
	}

	@Column(name = "type")
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "networkid")
	public Long getNetworkid() {
		return this.networkid;
	}

	public void setNetworkid(Long networkid) {
		this.networkid = networkid;
	}

	@Column(name = "networkaddress", length = 50)
	public String getNetworkaddress() {
		return this.networkaddress;
	}

	public void setNetworkaddress(String networkaddress) {
		this.networkaddress = networkaddress;
	}

	@Column(name = "state")
	public Long getState() {
		return this.state;
	}

	public void setState(Long state) {
		this.state = state;
	}

	@Column(name = "mapstodevice", length = 100)
	public String getMapstodevice() {
		return this.mapstodevice;
	}

	public void setMapstodevice(String mapstodevice) {
		this.mapstodevice = mapstodevice;
	}

	@Column(name = "senddevicealivemsg")
	public Boolean getSenddevicealivemsg() {
		return this.senddevicealivemsg;
	}

	public void setSenddevicealivemsg(Boolean senddevicealivemsg) {
		this.senddevicealivemsg = senddevicealivemsg;
	}

	@Column(name = "relayactivationperiod")
	public Long getRelayactivationperiod() {
		return this.relayactivationperiod;
	}

	public void setRelayactivationperiod(Long relayactivationperiod) {
		this.relayactivationperiod = relayactivationperiod;
	}

	@Column(name = "relaydelayperiod")
	public Long getRelaydelayperiod() {
		return this.relaydelayperiod;
	}

	public void setRelaydelayperiod(Long relaydelayperiod) {
		this.relaydelayperiod = relaydelayperiod;
	}

	@Column(name = "relaynormallyclosed")
	public Boolean getRelaynormallyclosed() {
		return this.relaynormallyclosed;
	}

	public void setRelaynormallyclosed(Boolean relaynormallyclosed) {
		this.relaynormallyclosed = relaynormallyclosed;
	}

	@Column(name = "pollfortagread")
	public Boolean getPollfortagread() {
		return this.pollfortagread;
	}

	public void setPollfortagread(Boolean pollfortagread) {
		this.pollfortagread = pollfortagread;
	}

	@Column(name = "sendtagoutoffieldmsg")
	public Boolean getSendtagoutoffieldmsg() {
		return this.sendtagoutoffieldmsg;
	}

	public void setSendtagoutoffieldmsg(Boolean sendtagoutoffieldmsg) {
		this.sendtagoutoffieldmsg = sendtagoutoffieldmsg;
	}

	@Column(name = "ledflashtime")
	public Long getLedflashtime() {
		return this.ledflashtime;
	}

	public void setLedflashtime(Long ledflashtime) {
		this.ledflashtime = ledflashtime;
	}

	@Column(name = "ledflashcolor")
	public Long getLedflashcolor() {
		return this.ledflashcolor;
	}

	public void setLedflashcolor(Long ledflashcolor) {
		this.ledflashcolor = ledflashcolor;
	}

	@Column(name = "buzzertime")
	public Long getBuzzertime() {
		return this.buzzertime;
	}

	public void setBuzzertime(Long buzzertime) {
		this.buzzertime = buzzertime;
	}

	@Column(name = "requiresconfigsync")
	public Boolean getRequiresconfigsync() {
		return this.requiresconfigsync;
	}

	public void setRequiresconfigsync(Boolean requiresconfigsync) {
		this.requiresconfigsync = requiresconfigsync;
	}

	@Column(name = "mapstoport")
	public Integer getMapstoport() {
		return this.mapstoport;
	}

	public void setMapstoport(Integer mapstoport) {
		this.mapstoport = mapstoport;
	}

	@Column(name = "securerelay")
	public Integer getSecurerelay() {
		return this.securerelay;
	}

	public void setSecurerelay(Integer securerelay) {
		this.securerelay = securerelay;
	}

	@Column(name = "global")
	public Integer getGlobal() {
		return this.global;
	}

	public void setGlobal(Integer global) {
		this.global = global;
	}

	@Column(name = "devicecn", length = 200)
	public String getDevicecn() {
		return this.devicecn;
	}

	public void setDevicecn(String devicecn) {
		this.devicecn = devicecn;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	@Column(name = "rs485_port_type")
	public Integer getRs485PortType() {
		return this.rs485PortType;
	}

	public void setRs485PortType(Integer rs485PortType) {
		this.rs485PortType = rs485PortType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "devices")
	public Set<Zonedevices> getZonedeviceses() {
		return this.zonedeviceses;
	}

	public void setZonedeviceses(Set<Zonedevices> zonedeviceses) {
		this.zonedeviceses = zonedeviceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "devices")
	public Set<Deviceports> getDeviceportses() {
		return this.deviceportses;
	}

	public void setDeviceportses(Set<Deviceports> deviceportses) {
		this.deviceportses = deviceportses;
	}

}
