package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Deviceports generated by hbm2java
 */
@Entity
@Table(name = "deviceports", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "deviceid"),
		@UniqueConstraint(columnNames = "portnumber"), @UniqueConstraint(columnNames = { "deviceid", "portnumber" }) })
public class Deviceports implements java.io.Serializable {

	private long id;
	private Devices devices;
	private int portnumber;
	private Boolean direction;
	private Boolean autoreportchange;
	private String description;
	private Long timevalue;
	private Boolean activatesrelay;
	private Boolean defaultlevel;
	private Long passthroughport;
	private Boolean supvmode;
	private Integer formatId;
	private Integer delayperiod;
	private Integer activateperiod;
	private Integer activaterelaynumber;
	private Boolean activatesled;
	private Boolean activatesbuzzer;
	private Integer activatelednumber;
	private Integer activatebuzzernumber;
	private Boolean supvready;
	private Integer opMode;
	private Set<Inputaction> inputactionsForConditiondev1 = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForResetReader = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForResetPort = new HashSet<Inputaction>(0);
	private Set<Devicestatus> devicestatusesForDeviceid = new HashSet<Devicestatus>(0);
	private Set<Inputaction> inputactionsForConditionstate2 = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForIndevice = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForInport = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForShuntDev = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForOutport = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForConditiondev2 = new HashSet<Inputaction>(0);
	private Set<Devicestatus> devicestatusesForPortnumber = new HashSet<Devicestatus>(0);
	private Set<Inputaction> inputactionsForConditionport1 = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForOutdevice = new HashSet<Inputaction>(0);
	private Set<Inputaction> inputactionsForShuntPort = new HashSet<Inputaction>(0);

	public Deviceports() {
	}

	public Deviceports(long id, Devices devices, int portnumber) {
		this.id = id;
		this.devices = devices;
		this.portnumber = portnumber;
	}

	public Deviceports(long id, Devices devices, int portnumber, Boolean direction, Boolean autoreportchange,
			String description, Long timevalue, Boolean activatesrelay, Boolean defaultlevel, Long passthroughport,
			Boolean supvmode, Integer formatId, Integer delayperiod, Integer activateperiod,
			Integer activaterelaynumber, Boolean activatesled, Boolean activatesbuzzer, Integer activatelednumber,
			Integer activatebuzzernumber, Boolean supvready, Integer opMode,
			Set<Inputaction> inputactionsForConditiondev1, Set<Inputaction> inputactionsForResetReader,
			Set<Inputaction> inputactionsForResetPort, Set<Devicestatus> devicestatusesForDeviceid,
			Set<Inputaction> inputactionsForConditionstate2, Set<Inputaction> inputactionsForIndevice,
			Set<Inputaction> inputactionsForInport, Set<Inputaction> inputactionsForShuntDev,
			Set<Inputaction> inputactionsForOutport, Set<Inputaction> inputactionsForConditiondev2,
			Set<Devicestatus> devicestatusesForPortnumber, Set<Inputaction> inputactionsForConditionport1,
			Set<Inputaction> inputactionsForOutdevice, Set<Inputaction> inputactionsForShuntPort) {
		this.id = id;
		this.devices = devices;
		this.portnumber = portnumber;
		this.direction = direction;
		this.autoreportchange = autoreportchange;
		this.description = description;
		this.timevalue = timevalue;
		this.activatesrelay = activatesrelay;
		this.defaultlevel = defaultlevel;
		this.passthroughport = passthroughport;
		this.supvmode = supvmode;
		this.formatId = formatId;
		this.delayperiod = delayperiod;
		this.activateperiod = activateperiod;
		this.activaterelaynumber = activaterelaynumber;
		this.activatesled = activatesled;
		this.activatesbuzzer = activatesbuzzer;
		this.activatelednumber = activatelednumber;
		this.activatebuzzernumber = activatebuzzernumber;
		this.supvready = supvready;
		this.opMode = opMode;
		this.inputactionsForConditiondev1 = inputactionsForConditiondev1;
		this.inputactionsForResetReader = inputactionsForResetReader;
		this.inputactionsForResetPort = inputactionsForResetPort;
		this.devicestatusesForDeviceid = devicestatusesForDeviceid;
		this.inputactionsForConditionstate2 = inputactionsForConditionstate2;
		this.inputactionsForIndevice = inputactionsForIndevice;
		this.inputactionsForInport = inputactionsForInport;
		this.inputactionsForShuntDev = inputactionsForShuntDev;
		this.inputactionsForOutport = inputactionsForOutport;
		this.inputactionsForConditiondev2 = inputactionsForConditiondev2;
		this.devicestatusesForPortnumber = devicestatusesForPortnumber;
		this.inputactionsForConditionport1 = inputactionsForConditionport1;
		this.inputactionsForOutdevice = inputactionsForOutdevice;
		this.inputactionsForShuntPort = inputactionsForShuntPort;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceid", unique = true, nullable = false)
	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	@Column(name = "portnumber", unique = true, nullable = false)
	public int getPortnumber() {
		return this.portnumber;
	}

	public void setPortnumber(int portnumber) {
		this.portnumber = portnumber;
	}

	@Column(name = "direction")
	public Boolean getDirection() {
		return this.direction;
	}

	public void setDirection(Boolean direction) {
		this.direction = direction;
	}

	@Column(name = "autoreportchange")
	public Boolean getAutoreportchange() {
		return this.autoreportchange;
	}

	public void setAutoreportchange(Boolean autoreportchange) {
		this.autoreportchange = autoreportchange;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "timevalue")
	public Long getTimevalue() {
		return this.timevalue;
	}

	public void setTimevalue(Long timevalue) {
		this.timevalue = timevalue;
	}

	@Column(name = "activatesrelay")
	public Boolean getActivatesrelay() {
		return this.activatesrelay;
	}

	public void setActivatesrelay(Boolean activatesrelay) {
		this.activatesrelay = activatesrelay;
	}

	@Column(name = "defaultlevel")
	public Boolean getDefaultlevel() {
		return this.defaultlevel;
	}

	public void setDefaultlevel(Boolean defaultlevel) {
		this.defaultlevel = defaultlevel;
	}

	@Column(name = "passthroughport")
	public Long getPassthroughport() {
		return this.passthroughport;
	}

	public void setPassthroughport(Long passthroughport) {
		this.passthroughport = passthroughport;
	}

	@Column(name = "supvmode")
	public Boolean getSupvmode() {
		return this.supvmode;
	}

	public void setSupvmode(Boolean supvmode) {
		this.supvmode = supvmode;
	}

	@Column(name = "format_id")
	public Integer getFormatId() {
		return this.formatId;
	}

	public void setFormatId(Integer formatId) {
		this.formatId = formatId;
	}

	@Column(name = "delayperiod")
	public Integer getDelayperiod() {
		return this.delayperiod;
	}

	public void setDelayperiod(Integer delayperiod) {
		this.delayperiod = delayperiod;
	}

	@Column(name = "activateperiod")
	public Integer getActivateperiod() {
		return this.activateperiod;
	}

	public void setActivateperiod(Integer activateperiod) {
		this.activateperiod = activateperiod;
	}

	@Column(name = "activaterelaynumber")
	public Integer getActivaterelaynumber() {
		return this.activaterelaynumber;
	}

	public void setActivaterelaynumber(Integer activaterelaynumber) {
		this.activaterelaynumber = activaterelaynumber;
	}

	@Column(name = "activatesled")
	public Boolean getActivatesled() {
		return this.activatesled;
	}

	public void setActivatesled(Boolean activatesled) {
		this.activatesled = activatesled;
	}

	@Column(name = "activatesbuzzer")
	public Boolean getActivatesbuzzer() {
		return this.activatesbuzzer;
	}

	public void setActivatesbuzzer(Boolean activatesbuzzer) {
		this.activatesbuzzer = activatesbuzzer;
	}

	@Column(name = "activatelednumber")
	public Integer getActivatelednumber() {
		return this.activatelednumber;
	}

	public void setActivatelednumber(Integer activatelednumber) {
		this.activatelednumber = activatelednumber;
	}

	@Column(name = "activatebuzzernumber")
	public Integer getActivatebuzzernumber() {
		return this.activatebuzzernumber;
	}

	public void setActivatebuzzernumber(Integer activatebuzzernumber) {
		this.activatebuzzernumber = activatebuzzernumber;
	}

	@Column(name = "supvready")
	public Boolean getSupvready() {
		return this.supvready;
	}

	public void setSupvready(Boolean supvready) {
		this.supvready = supvready;
	}

	@Column(name = "op_mode")
	public Integer getOpMode() {
		return this.opMode;
	}

	public void setOpMode(Integer opMode) {
		this.opMode = opMode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByConditiondev1")
	public Set<Inputaction> getInputactionsForConditiondev1() {
		return this.inputactionsForConditiondev1;
	}

	public void setInputactionsForConditiondev1(Set<Inputaction> inputactionsForConditiondev1) {
		this.inputactionsForConditiondev1 = inputactionsForConditiondev1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByResetReader")
	public Set<Inputaction> getInputactionsForResetReader() {
		return this.inputactionsForResetReader;
	}

	public void setInputactionsForResetReader(Set<Inputaction> inputactionsForResetReader) {
		this.inputactionsForResetReader = inputactionsForResetReader;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByResetPort")
	public Set<Inputaction> getInputactionsForResetPort() {
		return this.inputactionsForResetPort;
	}

	public void setInputactionsForResetPort(Set<Inputaction> inputactionsForResetPort) {
		this.inputactionsForResetPort = inputactionsForResetPort;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByDeviceid")
	public Set<Devicestatus> getDevicestatusesForDeviceid() {
		return this.devicestatusesForDeviceid;
	}

	public void setDevicestatusesForDeviceid(Set<Devicestatus> devicestatusesForDeviceid) {
		this.devicestatusesForDeviceid = devicestatusesForDeviceid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByConditionstate2")
	public Set<Inputaction> getInputactionsForConditionstate2() {
		return this.inputactionsForConditionstate2;
	}

	public void setInputactionsForConditionstate2(Set<Inputaction> inputactionsForConditionstate2) {
		this.inputactionsForConditionstate2 = inputactionsForConditionstate2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByIndevice")
	public Set<Inputaction> getInputactionsForIndevice() {
		return this.inputactionsForIndevice;
	}

	public void setInputactionsForIndevice(Set<Inputaction> inputactionsForIndevice) {
		this.inputactionsForIndevice = inputactionsForIndevice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByInport")
	public Set<Inputaction> getInputactionsForInport() {
		return this.inputactionsForInport;
	}

	public void setInputactionsForInport(Set<Inputaction> inputactionsForInport) {
		this.inputactionsForInport = inputactionsForInport;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByShuntDev")
	public Set<Inputaction> getInputactionsForShuntDev() {
		return this.inputactionsForShuntDev;
	}

	public void setInputactionsForShuntDev(Set<Inputaction> inputactionsForShuntDev) {
		this.inputactionsForShuntDev = inputactionsForShuntDev;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByOutport")
	public Set<Inputaction> getInputactionsForOutport() {
		return this.inputactionsForOutport;
	}

	public void setInputactionsForOutport(Set<Inputaction> inputactionsForOutport) {
		this.inputactionsForOutport = inputactionsForOutport;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByConditiondev2")
	public Set<Inputaction> getInputactionsForConditiondev2() {
		return this.inputactionsForConditiondev2;
	}

	public void setInputactionsForConditiondev2(Set<Inputaction> inputactionsForConditiondev2) {
		this.inputactionsForConditiondev2 = inputactionsForConditiondev2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByPortnumber")
	public Set<Devicestatus> getDevicestatusesForPortnumber() {
		return this.devicestatusesForPortnumber;
	}

	public void setDevicestatusesForPortnumber(Set<Devicestatus> devicestatusesForPortnumber) {
		this.devicestatusesForPortnumber = devicestatusesForPortnumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByConditionport1")
	public Set<Inputaction> getInputactionsForConditionport1() {
		return this.inputactionsForConditionport1;
	}

	public void setInputactionsForConditionport1(Set<Inputaction> inputactionsForConditionport1) {
		this.inputactionsForConditionport1 = inputactionsForConditionport1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByOutdevice")
	public Set<Inputaction> getInputactionsForOutdevice() {
		return this.inputactionsForOutdevice;
	}

	public void setInputactionsForOutdevice(Set<Inputaction> inputactionsForOutdevice) {
		this.inputactionsForOutdevice = inputactionsForOutdevice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceportsByShuntPort")
	public Set<Inputaction> getInputactionsForShuntPort() {
		return this.inputactionsForShuntPort;
	}

	public void setInputactionsForShuntPort(Set<Inputaction> inputactionsForShuntPort) {
		this.inputactionsForShuntPort = inputactionsForShuntPort;
	}

}
