package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Devicestatus generated by hbm2java
 */
@Entity
@Table(name = "devicestatus", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "deviceid",
		"portnumber" }))
public class Devicestatus implements java.io.Serializable {

	private int id;
	private Deviceports deviceportsByDeviceid;
	private Deviceports deviceportsByPortnumber;
	private Integer state;
	private Long usnchanged;
	private Date eventtime;
	private Boolean online;
	private Integer status;
	private String statusmessage;
	private String info;

	public Devicestatus() {
	}

	public Devicestatus(int id, Deviceports deviceportsByDeviceid, Deviceports deviceportsByPortnumber) {
		this.id = id;
		this.deviceportsByDeviceid = deviceportsByDeviceid;
		this.deviceportsByPortnumber = deviceportsByPortnumber;
	}

	public Devicestatus(int id, Deviceports deviceportsByDeviceid, Deviceports deviceportsByPortnumber, Integer state,
			Long usnchanged, Date eventtime, Boolean online, Integer status, String statusmessage, String info) {
		this.id = id;
		this.deviceportsByDeviceid = deviceportsByDeviceid;
		this.deviceportsByPortnumber = deviceportsByPortnumber;
		this.state = state;
		this.usnchanged = usnchanged;
		this.eventtime = eventtime;
		this.online = online;
		this.status = status;
		this.statusmessage = statusmessage;
		this.info = info;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceid", nullable = false)
	public Deviceports getDeviceportsByDeviceid() {
		return this.deviceportsByDeviceid;
	}

	public void setDeviceportsByDeviceid(Deviceports deviceportsByDeviceid) {
		this.deviceportsByDeviceid = deviceportsByDeviceid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portnumber", nullable = false)
	public Deviceports getDeviceportsByPortnumber() {
		return this.deviceportsByPortnumber;
	}

	public void setDeviceportsByPortnumber(Deviceports deviceportsByPortnumber) {
		this.deviceportsByPortnumber = deviceportsByPortnumber;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eventtime", length = 35)
	public Date getEventtime() {
		return this.eventtime;
	}

	public void setEventtime(Date eventtime) {
		this.eventtime = eventtime;
	}

	@Column(name = "online")
	public Boolean getOnline() {
		return this.online;
	}

	public void setOnline(Boolean online) {
		this.online = online;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "statusmessage", length = 100)
	public String getStatusmessage() {
		return this.statusmessage;
	}

	public void setStatusmessage(String statusmessage) {
		this.statusmessage = statusmessage;
	}

	@Column(name = "info")
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

}
