package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dvrservers generated by hbm2java
 */
@Entity
@Table(name = "dvrservers", schema = "public")
public class Dvrservers implements java.io.Serializable {

	private int serverid;
	private String ipaddress;
	private Integer port;
	private String description;
	private String username;
	private String password;
	private Integer servertype;
	private String servername;
	private String servercn;
	private Integer siteid;

	public Dvrservers() {
	}

	public Dvrservers(int serverid) {
		this.serverid = serverid;
	}

	public Dvrservers(int serverid, String ipaddress, Integer port, String description, String username,
			String password, Integer servertype, String servername, String servercn, Integer siteid) {
		this.serverid = serverid;
		this.ipaddress = ipaddress;
		this.port = port;
		this.description = description;
		this.username = username;
		this.password = password;
		this.servertype = servertype;
		this.servername = servername;
		this.servercn = servercn;
		this.siteid = siteid;
	}

	@Id

	@Column(name = "serverid", unique = true, nullable = false)
	public int getServerid() {
		return this.serverid;
	}

	public void setServerid(int serverid) {
		this.serverid = serverid;
	}

	@Column(name = "ipaddress", length = 50)
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "servertype")
	public Integer getServertype() {
		return this.servertype;
	}

	public void setServertype(Integer servertype) {
		this.servertype = servertype;
	}

	@Column(name = "servername", length = 100)
	public String getServername() {
		return this.servername;
	}

	public void setServername(String servername) {
		this.servername = servername;
	}

	@Column(name = "servercn", length = 200)
	public String getServercn() {
		return this.servercn;
	}

	public void setServercn(String servercn) {
		this.servercn = servercn;
	}

	@Column(name = "siteid")
	public Integer getSiteid() {
		return this.siteid;
	}

	public void setSiteid(Integer siteid) {
		this.siteid = siteid;
	}

}
