package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Floorplans generated by hbm2java
 */
@Entity
@Table(name = "floorplans", schema = "public")
public class Floorplans implements java.io.Serializable {

	private String fpid;
	private String fpdesc;
	private Set<Portlocation> portlocations = new HashSet<Portlocation>(0);

	public Floorplans() {
	}

	public Floorplans(String fpid) {
		this.fpid = fpid;
	}

	public Floorplans(String fpid, String fpdesc, Set<Portlocation> portlocations) {
		this.fpid = fpid;
		this.fpdesc = fpdesc;
		this.portlocations = portlocations;
	}

	@Id

	@Column(name = "fpid", unique = true, nullable = false, length = 50)
	public String getFpid() {
		return this.fpid;
	}

	public void setFpid(String fpid) {
		this.fpid = fpid;
	}

	@Column(name = "fpdesc", length = 50)
	public String getFpdesc() {
		return this.fpdesc;
	}

	public void setFpdesc(String fpdesc) {
		this.fpdesc = fpdesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "floorplans")
	public Set<Portlocation> getPortlocations() {
		return this.portlocations;
	}

	public void setPortlocations(Set<Portlocation> portlocations) {
		this.portlocations = portlocations;
	}

}
