package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Gargroup generated by hbm2java
 */
@Entity
@Table(name = "gargroup", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "gargroup"))
public class Gargroup implements java.io.Serializable {

	private int id;
	private String gargroup;
	private String gardesc;
	private int siteid;
	private String groupname;
	private Set<Busguestaccess> busguestaccesses = new HashSet<Busguestaccess>(0);

	public Gargroup() {
	}

	public Gargroup(int id, String gargroup, int siteid, String groupname) {
		this.id = id;
		this.gargroup = gargroup;
		this.siteid = siteid;
		this.groupname = groupname;
	}

	public Gargroup(int id, String gargroup, String gardesc, int siteid, String groupname,
			Set<Busguestaccess> busguestaccesses) {
		this.id = id;
		this.gargroup = gargroup;
		this.gardesc = gardesc;
		this.siteid = siteid;
		this.groupname = groupname;
		this.busguestaccesses = busguestaccesses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "gargroup", unique = true, nullable = false, length = 35)
	public String getGargroup() {
		return this.gargroup;
	}

	public void setGargroup(String gargroup) {
		this.gargroup = gargroup;
	}

	@Column(name = "gardesc", length = 50)
	public String getGardesc() {
		return this.gardesc;
	}

	public void setGardesc(String gardesc) {
		this.gardesc = gardesc;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	@Column(name = "groupname", nullable = false, length = 50)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gargroup")
	public Set<Busguestaccess> getBusguestaccesses() {
		return this.busguestaccesses;
	}

	public void setBusguestaccesses(Set<Busguestaccess> busguestaccesses) {
		this.busguestaccesses = busguestaccesses;
	}

}
