package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Holidays generated by hbm2java
 */
@Entity
@Table(name = "holidays", schema = "public")
public class Holidays implements java.io.Serializable {

	private String holidayid;
	private Long definitiontype;
	private Long month;
	private Long day;
	private Long weekofmonth;
	private String description;
	private Integer enabled;
	private Long usnchanged;
	private String groupid;
	private int siteid;

	public Holidays() {
	}

	public Holidays(String holidayid, int siteid) {
		this.holidayid = holidayid;
		this.siteid = siteid;
	}

	public Holidays(String holidayid, Long definitiontype, Long month, Long day, Long weekofmonth, String description,
			Integer enabled, Long usnchanged, String groupid, int siteid) {
		this.holidayid = holidayid;
		this.definitiontype = definitiontype;
		this.month = month;
		this.day = day;
		this.weekofmonth = weekofmonth;
		this.description = description;
		this.enabled = enabled;
		this.usnchanged = usnchanged;
		this.groupid = groupid;
		this.siteid = siteid;
	}

	@Id

	@Column(name = "holidayid", unique = true, nullable = false, length = 20)
	public String getHolidayid() {
		return this.holidayid;
	}

	public void setHolidayid(String holidayid) {
		this.holidayid = holidayid;
	}

	@Column(name = "definitiontype")
	public Long getDefinitiontype() {
		return this.definitiontype;
	}

	public void setDefinitiontype(Long definitiontype) {
		this.definitiontype = definitiontype;
	}

	@Column(name = "month")
	public Long getMonth() {
		return this.month;
	}

	public void setMonth(Long month) {
		this.month = month;
	}

	@Column(name = "day")
	public Long getDay() {
		return this.day;
	}

	public void setDay(Long day) {
		this.day = day;
	}

	@Column(name = "weekofmonth")
	public Long getWeekofmonth() {
		return this.weekofmonth;
	}

	public void setWeekofmonth(Long weekofmonth) {
		this.weekofmonth = weekofmonth;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "enabled")
	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@Column(name = "groupid", length = 50)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

}
