package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Idspanels generated by hbm2java
 */
@Entity
@Table(name = "idspanels", schema = "public")
public class Idspanels implements java.io.Serializable {

	private long id;
	private String idsname;
	private String description;
	private String ip;
	private Integer port;
	private String username;
	private String password;
	private String idstype;
	private String pin;
	private String idscode;
	private Integer status;
	private Integer listenport;

	public Idspanels() {
	}

	public Idspanels(long id, String idsname, String ip, String idstype) {
		this.id = id;
		this.idsname = idsname;
		this.ip = ip;
		this.idstype = idstype;
	}

	public Idspanels(long id, String idsname, String description, String ip, Integer port, String username,
			String password, String idstype, String pin, String idscode, Integer status, Integer listenport) {
		this.id = id;
		this.idsname = idsname;
		this.description = description;
		this.ip = ip;
		this.port = port;
		this.username = username;
		this.password = password;
		this.idstype = idstype;
		this.pin = pin;
		this.idscode = idscode;
		this.status = status;
		this.listenport = listenport;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "idsname", nullable = false, length = 100)
	public String getIdsname() {
		return this.idsname;
	}

	public void setIdsname(String idsname) {
		this.idsname = idsname;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ip", nullable = false, length = 50)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "idstype", nullable = false, length = 50)
	public String getIdstype() {
		return this.idstype;
	}

	public void setIdstype(String idstype) {
		this.idstype = idstype;
	}

	@Column(name = "pin", length = 30)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "idscode", length = 30)
	public String getIdscode() {
		return this.idscode;
	}

	public void setIdscode(String idscode) {
		this.idscode = idscode;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "listenport")
	public Integer getListenport() {
		return this.listenport;
	}

	public void setListenport(Integer listenport) {
		this.listenport = listenport;
	}

}
