package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ldapgroups generated by hbm2java
 */
@Entity
@Table(name = "ldapgroups", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "groupid"),
		@UniqueConstraint(columnNames = "name") })
public class Ldapgroups implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean syncuser;
	private Boolean syncadminuser;
	private String groupid;
	private Set<Accessgroupldapgroups> accessgroupldapgroupses = new HashSet<Accessgroupldapgroups>(0);
	private Set<Userldapgroups> userldapgroupses = new HashSet<Userldapgroups>(0);

	public Ldapgroups() {
	}

	public Ldapgroups(int id, String name, String groupid) {
		this.id = id;
		this.name = name;
		this.groupid = groupid;
	}

	public Ldapgroups(int id, String name, Boolean syncuser, Boolean syncadminuser, String groupid,
			Set<Accessgroupldapgroups> accessgroupldapgroupses, Set<Userldapgroups> userldapgroupses) {
		this.id = id;
		this.name = name;
		this.syncuser = syncuser;
		this.syncadminuser = syncadminuser;
		this.groupid = groupid;
		this.accessgroupldapgroupses = accessgroupldapgroupses;
		this.userldapgroupses = userldapgroupses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "syncuser")
	public Boolean getSyncuser() {
		return this.syncuser;
	}

	public void setSyncuser(Boolean syncuser) {
		this.syncuser = syncuser;
	}

	@Column(name = "syncadminuser")
	public Boolean getSyncadminuser() {
		return this.syncadminuser;
	}

	public void setSyncadminuser(Boolean syncadminuser) {
		this.syncadminuser = syncadminuser;
	}

	@Column(name = "groupid", unique = true, nullable = false, length = 200)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ldapgroups")
	public Set<Accessgroupldapgroups> getAccessgroupldapgroupses() {
		return this.accessgroupldapgroupses;
	}

	public void setAccessgroupldapgroupses(Set<Accessgroupldapgroups> accessgroupldapgroupses) {
		this.accessgroupldapgroupses = accessgroupldapgroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ldapgroups")
	public Set<Userldapgroups> getUserldapgroupses() {
		return this.userldapgroupses;
	}

	public void setUserldapgroupses(Set<Userldapgroups> userldapgroupses) {
		this.userldapgroupses = userldapgroupses;
	}

}
