package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Logs generated by hbm2java
 */
@Entity
@Table(name = "logs", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "serverid", "log_id" }))
public class Logs implements java.io.Serializable {

	private long logId;
	private String serverid;
	private Date logtime;
	private String activitytype;
	private String deviceid;
	private String devicename;
	private String portname;
	private String info;
	private String origname;
	private String result;
	private String snapshot;
	private String severity;
	private String level;
	private Integer logtype;
	private String suiteid;
	private String userid;
	private String lastname;
	private String firstname;
	private String cardnumber;
	private Boolean sent;
	private Long instructionId;
	private Boolean ackrequired;
	private String devicetype;
	private String iocontrol;

	public Logs() {
	}

	public Logs(long logId, String serverid, Date logtime) {
		this.logId = logId;
		this.serverid = serverid;
		this.logtime = logtime;
	}

	public Logs(long logId, String serverid, Date logtime, String activitytype, String deviceid, String devicename,
			String portname, String info, String origname, String result, String snapshot, String severity,
			String level, Integer logtype, String suiteid, String userid, String lastname, String firstname,
			String cardnumber, Boolean sent, Long instructionId, Boolean ackrequired, String devicetype,
			String iocontrol) {
		this.logId = logId;
		this.serverid = serverid;
		this.logtime = logtime;
		this.activitytype = activitytype;
		this.deviceid = deviceid;
		this.devicename = devicename;
		this.portname = portname;
		this.info = info;
		this.origname = origname;
		this.result = result;
		this.snapshot = snapshot;
		this.severity = severity;
		this.level = level;
		this.logtype = logtype;
		this.suiteid = suiteid;
		this.userid = userid;
		this.lastname = lastname;
		this.firstname = firstname;
		this.cardnumber = cardnumber;
		this.sent = sent;
		this.instructionId = instructionId;
		this.ackrequired = ackrequired;
		this.devicetype = devicetype;
		this.iocontrol = iocontrol;
	}

	@Id

	@Column(name = "log_id", unique = true, nullable = false)
	public long getLogId() {
		return this.logId;
	}

	public void setLogId(long logId) {
		this.logId = logId;
	}

	@Column(name = "serverid", nullable = false, length = 50)
	public String getServerid() {
		return this.serverid;
	}

	public void setServerid(String serverid) {
		this.serverid = serverid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logtime", nullable = false, length = 29)
	public Date getLogtime() {
		return this.logtime;
	}

	public void setLogtime(Date logtime) {
		this.logtime = logtime;
	}

	@Column(name = "activitytype", length = 20)
	public String getActivitytype() {
		return this.activitytype;
	}

	public void setActivitytype(String activitytype) {
		this.activitytype = activitytype;
	}

	@Column(name = "deviceid", length = 100)
	public String getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	@Column(name = "devicename", length = 100)
	public String getDevicename() {
		return this.devicename;
	}

	public void setDevicename(String devicename) {
		this.devicename = devicename;
	}

	@Column(name = "portname", length = 50)
	public String getPortname() {
		return this.portname;
	}

	public void setPortname(String portname) {
		this.portname = portname;
	}

	@Column(name = "info", length = 400)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "origname", length = 50)
	public String getOrigname() {
		return this.origname;
	}

	public void setOrigname(String origname) {
		this.origname = origname;
	}

	@Column(name = "result", length = 50)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "snapshot", length = 50)
	public String getSnapshot() {
		return this.snapshot;
	}

	public void setSnapshot(String snapshot) {
		this.snapshot = snapshot;
	}

	@Column(name = "severity", length = 50)
	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	@Column(name = "level", length = 20)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "logtype")
	public Integer getLogtype() {
		return this.logtype;
	}

	public void setLogtype(Integer logtype) {
		this.logtype = logtype;
	}

	@Column(name = "suiteid", length = 50)
	public String getSuiteid() {
		return this.suiteid;
	}

	public void setSuiteid(String suiteid) {
		this.suiteid = suiteid;
	}

	@Column(name = "userid", length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "cardnumber", length = 100)
	public String getCardnumber() {
		return this.cardnumber;
	}

	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}

	@Column(name = "sent")
	public Boolean getSent() {
		return this.sent;
	}

	public void setSent(Boolean sent) {
		this.sent = sent;
	}

	@Column(name = "instruction_id")
	public Long getInstructionId() {
		return this.instructionId;
	}

	public void setInstructionId(Long instructionId) {
		this.instructionId = instructionId;
	}

	@Column(name = "ackrequired")
	public Boolean getAckrequired() {
		return this.ackrequired;
	}

	public void setAckrequired(Boolean ackrequired) {
		this.ackrequired = ackrequired;
	}

	@Column(name = "devicetype", length = 50)
	public String getDevicetype() {
		return this.devicetype;
	}

	public void setDevicetype(String devicetype) {
		this.devicetype = devicetype;
	}

	@Column(name = "iocontrol", length = 2)
	public String getIocontrol() {
		return this.iocontrol;
	}

	public void setIocontrol(String iocontrol) {
		this.iocontrol = iocontrol;
	}

}
