package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mapicons generated by hbm2java
 */
@Entity
@Table(name = "mapicons", schema = "public")
public class Mapicons implements java.io.Serializable {

	private long id;
	private String image;

	public Mapicons() {
	}

	public Mapicons(long id) {
		this.id = id;
	}

	public Mapicons(long id, String image) {
		this.id = id;
		this.image = image;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
