package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Maps generated by hbm2java
 */
@Entity
@Table(name = "maps", schema = "public")
public class Maps implements java.io.Serializable {

	private long id;
	private Maps maps;
	private String name;
	private String description;
	private short floornum;
	private String image;
	private int siteid;
	private Long mapgroupid;
	private Set<Mapzones> mapzoneses = new HashSet<Mapzones>(0);
	private Set<Maps> mapses = new HashSet<Maps>(0);

	public Maps() {
	}

	public Maps(long id, String name, short floornum, String image, int siteid) {
		this.id = id;
		this.name = name;
		this.floornum = floornum;
		this.image = image;
		this.siteid = siteid;
	}

	public Maps(long id, Maps maps, String name, String description, short floornum, String image, int siteid,
			Long mapgroupid, Set<Mapzones> mapzoneses, Set<Maps> mapses) {
		this.id = id;
		this.maps = maps;
		this.name = name;
		this.description = description;
		this.floornum = floornum;
		this.image = image;
		this.siteid = siteid;
		this.mapgroupid = mapgroupid;
		this.mapzoneses = mapzoneses;
		this.mapses = mapses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent")
	public Maps getMaps() {
		return this.maps;
	}

	public void setMaps(Maps maps) {
		this.maps = maps;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "floornum", nullable = false)
	public short getFloornum() {
		return this.floornum;
	}

	public void setFloornum(short floornum) {
		this.floornum = floornum;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	@Column(name = "mapgroupid")
	public Long getMapgroupid() {
		return this.mapgroupid;
	}

	public void setMapgroupid(Long mapgroupid) {
		this.mapgroupid = mapgroupid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maps")
	public Set<Mapzones> getMapzoneses() {
		return this.mapzoneses;
	}

	public void setMapzoneses(Set<Mapzones> mapzoneses) {
		this.mapzoneses = mapzoneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maps")
	public Set<Maps> getMapses() {
		return this.mapses;
	}

	public void setMapses(Set<Maps> mapses) {
		this.mapses = mapses;
	}

}
