package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Panels generated by hbm2java
 */
@Entity
@Table(name = "panels", schema = "public")
public class Panels implements java.io.Serializable {

	private String panelid;
	private String description;
	private Long accesskeypress1;
	private Long accesskeypress2;
	private Long relay1;
	private Long relay2;
	private Long talktime;
	private Integer global;
	private int siteid;
	private Set<Zonepanels> zonepanelses = new HashSet<Zonepanels>(0);

	public Panels() {
	}

	public Panels(String panelid, int siteid) {
		this.panelid = panelid;
		this.siteid = siteid;
	}

	public Panels(String panelid, String description, Long accesskeypress1, Long accesskeypress2, Long relay1,
			Long relay2, Long talktime, Integer global, int siteid, Set<Zonepanels> zonepanelses) {
		this.panelid = panelid;
		this.description = description;
		this.accesskeypress1 = accesskeypress1;
		this.accesskeypress2 = accesskeypress2;
		this.relay1 = relay1;
		this.relay2 = relay2;
		this.talktime = talktime;
		this.global = global;
		this.siteid = siteid;
		this.zonepanelses = zonepanelses;
	}

	@Id

	@Column(name = "panelid", unique = true, nullable = false, length = 50)
	public String getPanelid() {
		return this.panelid;
	}

	public void setPanelid(String panelid) {
		this.panelid = panelid;
	}

	@Column(name = "description", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "accesskeypress1")
	public Long getAccesskeypress1() {
		return this.accesskeypress1;
	}

	public void setAccesskeypress1(Long accesskeypress1) {
		this.accesskeypress1 = accesskeypress1;
	}

	@Column(name = "accesskeypress2")
	public Long getAccesskeypress2() {
		return this.accesskeypress2;
	}

	public void setAccesskeypress2(Long accesskeypress2) {
		this.accesskeypress2 = accesskeypress2;
	}

	@Column(name = "relay1")
	public Long getRelay1() {
		return this.relay1;
	}

	public void setRelay1(Long relay1) {
		this.relay1 = relay1;
	}

	@Column(name = "relay2")
	public Long getRelay2() {
		return this.relay2;
	}

	public void setRelay2(Long relay2) {
		this.relay2 = relay2;
	}

	@Column(name = "talktime")
	public Long getTalktime() {
		return this.talktime;
	}

	public void setTalktime(Long talktime) {
		this.talktime = talktime;
	}

	@Column(name = "global")
	public Integer getGlobal() {
		return this.global;
	}

	public void setGlobal(Integer global) {
		this.global = global;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "panels")
	public Set<Zonepanels> getZonepanelses() {
		return this.zonepanelses;
	}

	public void setZonepanelses(Set<Zonepanels> zonepanelses) {
		this.zonepanelses = zonepanelses;
	}

}
