package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pivconfig generated by hbm2java
 */
@Entity
@Table(name = "pivconfig", schema = "public")
public class Pivconfig implements java.io.Serializable {

	private long id;
	private boolean ocspEnabled;
	private int crlInterval;
	private boolean allowChainErr;
	private boolean allowSignatureErr;
	private Boolean cacheStatus;
	private Integer cacheStatusFreq;
	private Boolean denyOnOcspTimeout;
	private Integer pdTimeout;

	public Pivconfig() {
	}

	public Pivconfig(long id, boolean ocspEnabled, int crlInterval, boolean allowChainErr, boolean allowSignatureErr) {
		this.id = id;
		this.ocspEnabled = ocspEnabled;
		this.crlInterval = crlInterval;
		this.allowChainErr = allowChainErr;
		this.allowSignatureErr = allowSignatureErr;
	}

	public Pivconfig(long id, boolean ocspEnabled, int crlInterval, boolean allowChainErr, boolean allowSignatureErr,
			Boolean cacheStatus, Integer cacheStatusFreq, Boolean denyOnOcspTimeout, Integer pdTimeout) {
		this.id = id;
		this.ocspEnabled = ocspEnabled;
		this.crlInterval = crlInterval;
		this.allowChainErr = allowChainErr;
		this.allowSignatureErr = allowSignatureErr;
		this.cacheStatus = cacheStatus;
		this.cacheStatusFreq = cacheStatusFreq;
		this.denyOnOcspTimeout = denyOnOcspTimeout;
		this.pdTimeout = pdTimeout;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ocsp_enabled", nullable = false)
	public boolean isOcspEnabled() {
		return this.ocspEnabled;
	}

	public void setOcspEnabled(boolean ocspEnabled) {
		this.ocspEnabled = ocspEnabled;
	}

	@Column(name = "crl_interval", nullable = false)
	public int getCrlInterval() {
		return this.crlInterval;
	}

	public void setCrlInterval(int crlInterval) {
		this.crlInterval = crlInterval;
	}

	@Column(name = "allow_chain_err", nullable = false)
	public boolean isAllowChainErr() {
		return this.allowChainErr;
	}

	public void setAllowChainErr(boolean allowChainErr) {
		this.allowChainErr = allowChainErr;
	}

	@Column(name = "allow_signature_err", nullable = false)
	public boolean isAllowSignatureErr() {
		return this.allowSignatureErr;
	}

	public void setAllowSignatureErr(boolean allowSignatureErr) {
		this.allowSignatureErr = allowSignatureErr;
	}

	@Column(name = "cache_status")
	public Boolean getCacheStatus() {
		return this.cacheStatus;
	}

	public void setCacheStatus(Boolean cacheStatus) {
		this.cacheStatus = cacheStatus;
	}

	@Column(name = "cache_status_freq")
	public Integer getCacheStatusFreq() {
		return this.cacheStatusFreq;
	}

	public void setCacheStatusFreq(Integer cacheStatusFreq) {
		this.cacheStatusFreq = cacheStatusFreq;
	}

	@Column(name = "deny_on_ocsp_timeout")
	public Boolean getDenyOnOcspTimeout() {
		return this.denyOnOcspTimeout;
	}

	public void setDenyOnOcspTimeout(Boolean denyOnOcspTimeout) {
		this.denyOnOcspTimeout = denyOnOcspTimeout;
	}

	@Column(name = "pd_timeout")
	public Integer getPdTimeout() {
		return this.pdTimeout;
	}

	public void setPdTimeout(Integer pdTimeout) {
		this.pdTimeout = pdTimeout;
	}

}
