package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Portlocation generated by hbm2java
 */
@Entity
@Table(name = "portlocation", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "devid",
		"port" }))
public class Portlocation implements java.io.Serializable {

	private long id;
	private Floorplans floorplans;
	private String devid;
	private Integer port;
	private Integer x;
	private Integer y;
	private Integer state;
	private Integer alarm;

	public Portlocation() {
	}

	public Portlocation(long id) {
		this.id = id;
	}

	public Portlocation(long id, Floorplans floorplans, String devid, Integer port, Integer x, Integer y, Integer state,
			Integer alarm) {
		this.id = id;
		this.floorplans = floorplans;
		this.devid = devid;
		this.port = port;
		this.x = x;
		this.y = y;
		this.state = state;
		this.alarm = alarm;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fpid")
	public Floorplans getFloorplans() {
		return this.floorplans;
	}

	public void setFloorplans(Floorplans floorplans) {
		this.floorplans = floorplans;
	}

	@Column(name = "devid", length = 50)
	public String getDevid() {
		return this.devid;
	}

	public void setDevid(String devid) {
		this.devid = devid;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@Column(name = "x")
	public Integer getX() {
		return this.x;
	}

	public void setX(Integer x) {
		this.x = x;
	}

	@Column(name = "y")
	public Integer getY() {
		return this.y;
	}

	public void setY(Integer y) {
		this.y = y;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "alarm")
	public Integer getAlarm() {
		return this.alarm;
	}

	public void setAlarm(Integer alarm) {
		this.alarm = alarm;
	}

}
