package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rargroup generated by hbm2java
 */
@Entity
@Table(name = "rargroup", schema = "public")
public class Rargroup implements java.io.Serializable {

	private String rargroup;
	private long id;
	private String rardesc;
	private String groupid;
	private Long usnchanged;
	private Integer alertlevels;
	private int siteid;
	private Set<Useraccessgroups> useraccessgroupses = new HashSet<Useraccessgroups>(0);
	private Set<Zonegroupexempt> zonegroupexempts = new HashSet<Zonegroupexempt>(0);
	private Set<Mustertemplates> mustertemplateses = new HashSet<Mustertemplates>(0);
	private Set<Bususeraccess> bususeraccesses = new HashSet<Bususeraccess>(0);
	private Set<Inputaction> inputactions = new HashSet<Inputaction>(0);
	private Set<Useraccessrights> useraccessrightses = new HashSet<Useraccessrights>(0);
	private Set<Accessgroupldaporganizationunits> accessgroupldaporganizationunitses = new HashSet<Accessgroupldaporganizationunits>(
			0);
	private Set<Accessgroupldapgroups> accessgroupldapgroupses = new HashSet<Accessgroupldapgroups>(0);

	public Rargroup() {
	}

	public Rargroup(String rargroup, long id, int siteid) {
		this.rargroup = rargroup;
		this.id = id;
		this.siteid = siteid;
	}

	public Rargroup(String rargroup, long id, String rardesc, String groupid, Long usnchanged, Integer alertlevels,
			int siteid, Set<Useraccessgroups> useraccessgroupses, Set<Zonegroupexempt> zonegroupexempts,
			Set<Mustertemplates> mustertemplateses, Set<Bususeraccess> bususeraccesses, Set<Inputaction> inputactions,
			Set<Useraccessrights> useraccessrightses,
			Set<Accessgroupldaporganizationunits> accessgroupldaporganizationunitses,
			Set<Accessgroupldapgroups> accessgroupldapgroupses) {
		this.rargroup = rargroup;
		this.id = id;
		this.rardesc = rardesc;
		this.groupid = groupid;
		this.usnchanged = usnchanged;
		this.alertlevels = alertlevels;
		this.siteid = siteid;
		this.useraccessgroupses = useraccessgroupses;
		this.zonegroupexempts = zonegroupexempts;
		this.mustertemplateses = mustertemplateses;
		this.bususeraccesses = bususeraccesses;
		this.inputactions = inputactions;
		this.useraccessrightses = useraccessrightses;
		this.accessgroupldaporganizationunitses = accessgroupldaporganizationunitses;
		this.accessgroupldapgroupses = accessgroupldapgroupses;
	}

	@Id

	@Column(name = "rargroup", unique = true, nullable = false, length = 100)
	public String getRargroup() {
		return this.rargroup;
	}

	public void setRargroup(String rargroup) {
		this.rargroup = rargroup;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "rardesc", length = 100)
	public String getRardesc() {
		return this.rardesc;
	}

	public void setRardesc(String rardesc) {
		this.rardesc = rardesc;
	}

	@Column(name = "groupid", length = 200)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@Column(name = "alertlevels")
	public Integer getAlertlevels() {
		return this.alertlevels;
	}

	public void setAlertlevels(Integer alertlevels) {
		this.alertlevels = alertlevels;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rargroup")
	public Set<Useraccessgroups> getUseraccessgroupses() {
		return this.useraccessgroupses;
	}

	public void setUseraccessgroupses(Set<Useraccessgroups> useraccessgroupses) {
		this.useraccessgroupses = useraccessgroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rargroup")
	public Set<Zonegroupexempt> getZonegroupexempts() {
		return this.zonegroupexempts;
	}

	public void setZonegroupexempts(Set<Zonegroupexempt> zonegroupexempts) {
		this.zonegroupexempts = zonegroupexempts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rargroup")
	public Set<Mustertemplates> getMustertemplateses() {
		return this.mustertemplateses;
	}

	public void setMustertemplateses(Set<Mustertemplates> mustertemplateses) {
		this.mustertemplateses = mustertemplateses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rargroup")
	public Set<Bususeraccess> getBususeraccesses() {
		return this.bususeraccesses;
	}

	public void setBususeraccesses(Set<Bususeraccess> bususeraccesses) {
		this.bususeraccesses = bususeraccesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rargroup")
	public Set<Inputaction> getInputactions() {
		return this.inputactions;
	}

	public void setInputactions(Set<Inputaction> inputactions) {
		this.inputactions = inputactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rargroup")
	public Set<Useraccessrights> getUseraccessrightses() {
		return this.useraccessrightses;
	}

	public void setUseraccessrightses(Set<Useraccessrights> useraccessrightses) {
		this.useraccessrightses = useraccessrightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rargroup")
	public Set<Accessgroupldaporganizationunits> getAccessgroupldaporganizationunitses() {
		return this.accessgroupldaporganizationunitses;
	}

	public void setAccessgroupldaporganizationunitses(
			Set<Accessgroupldaporganizationunits> accessgroupldaporganizationunitses) {
		this.accessgroupldaporganizationunitses = accessgroupldaporganizationunitses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rargroup")
	public Set<Accessgroupldapgroups> getAccessgroupldapgroupses() {
		return this.accessgroupldapgroupses;
	}

	public void setAccessgroupldapgroupses(Set<Accessgroupldapgroups> accessgroupldapgroupses) {
		this.accessgroupldapgroupses = accessgroupldapgroupses;
	}

}
