package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sausers generated by hbm2java
 */
@Entity
@Table(name = "sausers", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "sagid", "userid" }))
public class Sausers implements java.io.Serializable {

	private long id;
	private Sagroup sagroup;
	private Users users;

	public Sausers() {
	}

	public Sausers(long id) {
		this.id = id;
	}

	public Sausers(long id, Sagroup sagroup, Users users) {
		this.id = id;
		this.sagroup = sagroup;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sagid")
	public Sagroup getSagroup() {
		return this.sagroup;
	}

	public void setSagroup(Sagroup sagroup) {
		this.sagroup = sagroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
