package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Scheduleperiods generated by hbm2java
 */
@Entity
@Table(name = "scheduleperiods", schema = "public")
public class Scheduleperiods implements java.io.Serializable {

	private String periodid;
	private Schedule schedule;
	private Integer frequency;
	private Integer frequencyexceptions;
	private Integer frequencyday;
	private Integer frequencyexceptionsday;
	private Date ontime;
	private Date offtime;
	private Integer enabled;
	private String description;

	public Scheduleperiods() {
	}

	public Scheduleperiods(String periodid) {
		this.periodid = periodid;
	}

	public Scheduleperiods(String periodid, Schedule schedule, Integer frequency, Integer frequencyexceptions,
			Integer frequencyday, Integer frequencyexceptionsday, Date ontime, Date offtime, Integer enabled,
			String description) {
		this.periodid = periodid;
		this.schedule = schedule;
		this.frequency = frequency;
		this.frequencyexceptions = frequencyexceptions;
		this.frequencyday = frequencyday;
		this.frequencyexceptionsday = frequencyexceptionsday;
		this.ontime = ontime;
		this.offtime = offtime;
		this.enabled = enabled;
		this.description = description;
	}

	@Id

	@Column(name = "periodid", unique = true, nullable = false, length = 25)
	public String getPeriodid() {
		return this.periodid;
	}

	public void setPeriodid(String periodid) {
		this.periodid = periodid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scheduleid")
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@Column(name = "frequency")
	public Integer getFrequency() {
		return this.frequency;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	@Column(name = "frequencyexceptions")
	public Integer getFrequencyexceptions() {
		return this.frequencyexceptions;
	}

	public void setFrequencyexceptions(Integer frequencyexceptions) {
		this.frequencyexceptions = frequencyexceptions;
	}

	@Column(name = "frequencyday")
	public Integer getFrequencyday() {
		return this.frequencyday;
	}

	public void setFrequencyday(Integer frequencyday) {
		this.frequencyday = frequencyday;
	}

	@Column(name = "frequencyexceptionsday")
	public Integer getFrequencyexceptionsday() {
		return this.frequencyexceptionsday;
	}

	public void setFrequencyexceptionsday(Integer frequencyexceptionsday) {
		this.frequencyexceptionsday = frequencyexceptionsday;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ontime", length = 29)
	public Date getOntime() {
		return this.ontime;
	}

	public void setOntime(Date ontime) {
		this.ontime = ontime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "offtime", length = 29)
	public Date getOfftime() {
		return this.offtime;
	}

	public void setOfftime(Date offtime) {
		this.offtime = offtime;
	}

	@Column(name = "enabled")
	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
