package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "scheduleid"))
public class Schedule implements java.io.Serializable {

	private int id;
	private String scheduleid;
	private String scheduledesc;
	private String schedid;
	private Long usnchanged;
	private int siteid;
	private Set<Caschedules> cascheduleses = new HashSet<Caschedules>(0);
	private Set<Flooraccessrights> flooraccessrightses = new HashSet<Flooraccessrights>(0);
	private Set<Inputaction> inputactions = new HashSet<Inputaction>(0);
	private Set<Useraccessrights> useraccessrightses = new HashSet<Useraccessrights>(0);
	private Set<Guestaccessrights> guestaccessrightses = new HashSet<Guestaccessrights>(0);
	private Set<Scheduleperiods> scheduleperiodses = new HashSet<Scheduleperiods>(0);

	public Schedule() {
	}

	public Schedule(int id, String scheduleid, int siteid) {
		this.id = id;
		this.scheduleid = scheduleid;
		this.siteid = siteid;
	}

	public Schedule(int id, String scheduleid, String scheduledesc, String schedid, Long usnchanged, int siteid,
			Set<Caschedules> cascheduleses, Set<Flooraccessrights> flooraccessrightses, Set<Inputaction> inputactions,
			Set<Useraccessrights> useraccessrightses, Set<Guestaccessrights> guestaccessrightses,
			Set<Scheduleperiods> scheduleperiodses) {
		this.id = id;
		this.scheduleid = scheduleid;
		this.scheduledesc = scheduledesc;
		this.schedid = schedid;
		this.usnchanged = usnchanged;
		this.siteid = siteid;
		this.cascheduleses = cascheduleses;
		this.flooraccessrightses = flooraccessrightses;
		this.inputactions = inputactions;
		this.useraccessrightses = useraccessrightses;
		this.guestaccessrightses = guestaccessrightses;
		this.scheduleperiodses = scheduleperiodses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "scheduleid", unique = true, nullable = false, length = 50)
	public String getScheduleid() {
		return this.scheduleid;
	}

	public void setScheduleid(String scheduleid) {
		this.scheduleid = scheduleid;
	}

	@Column(name = "scheduledesc", length = 80)
	public String getScheduledesc() {
		return this.scheduledesc;
	}

	public void setScheduledesc(String scheduledesc) {
		this.scheduledesc = scheduledesc;
	}

	@Column(name = "schedid", length = 200)
	public String getSchedid() {
		return this.schedid;
	}

	public void setSchedid(String schedid) {
		this.schedid = schedid;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<Caschedules> getCascheduleses() {
		return this.cascheduleses;
	}

	public void setCascheduleses(Set<Caschedules> cascheduleses) {
		this.cascheduleses = cascheduleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<Flooraccessrights> getFlooraccessrightses() {
		return this.flooraccessrightses;
	}

	public void setFlooraccessrightses(Set<Flooraccessrights> flooraccessrightses) {
		this.flooraccessrightses = flooraccessrightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<Inputaction> getInputactions() {
		return this.inputactions;
	}

	public void setInputactions(Set<Inputaction> inputactions) {
		this.inputactions = inputactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<Useraccessrights> getUseraccessrightses() {
		return this.useraccessrightses;
	}

	public void setUseraccessrightses(Set<Useraccessrights> useraccessrightses) {
		this.useraccessrightses = useraccessrightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<Guestaccessrights> getGuestaccessrightses() {
		return this.guestaccessrightses;
	}

	public void setGuestaccessrightses(Set<Guestaccessrights> guestaccessrightses) {
		this.guestaccessrightses = guestaccessrightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<Scheduleperiods> getScheduleperiodses() {
		return this.scheduleperiodses;
	}

	public void setScheduleperiodses(Set<Scheduleperiods> scheduleperiodses) {
		this.scheduleperiodses = scheduleperiodses;
	}

}
