package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Suitefloorgroups generated by hbm2java
 */
@Entity
@Table(name = "suitefloorgroups", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "suiteid",
		"fargroup" }))
public class Suitefloorgroups implements java.io.Serializable {

	private long id;
	private Fargroup fargroup;
	private Suites suites;

	public Suitefloorgroups() {
	}

	public Suitefloorgroups(long id, Fargroup fargroup, Suites suites) {
		this.id = id;
		this.fargroup = fargroup;
		this.suites = suites;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fargroup", nullable = false)
	public Fargroup getFargroup() {
		return this.fargroup;
	}

	public void setFargroup(Fargroup fargroup) {
		this.fargroup = fargroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suiteid", nullable = false)
	public Suites getSuites() {
		return this.suites;
	}

	public void setSuites(Suites suites) {
		this.suites = suites;
	}

}
