package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Suites generated by hbm2java
 */
@Entity
@Table(name = "suites", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "siteid",
		"suitecode" }))
public class Suites implements java.io.Serializable {

	private String suiteid;
	private Business business;
	private String suitecode;
	private String gargroup;
	private String altphonenumber;
	private String phonenumber;
	private Integer siteid;
	private String suitename;
	private String scheduleid;
	private Set<Suitefloorgroups> suitefloorgroupses = new HashSet<Suitefloorgroups>(0);

	public Suites() {
	}

	public Suites(String suiteid, String suitecode, String suitename) {
		this.suiteid = suiteid;
		this.suitecode = suitecode;
		this.suitename = suitename;
	}

	public Suites(String suiteid, Business business, String suitecode, String gargroup, String altphonenumber,
			String phonenumber, Integer siteid, String suitename, String scheduleid,
			Set<Suitefloorgroups> suitefloorgroupses) {
		this.suiteid = suiteid;
		this.business = business;
		this.suitecode = suitecode;
		this.gargroup = gargroup;
		this.altphonenumber = altphonenumber;
		this.phonenumber = phonenumber;
		this.siteid = siteid;
		this.suitename = suitename;
		this.scheduleid = scheduleid;
		this.suitefloorgroupses = suitefloorgroupses;
	}

	@Id

	@Column(name = "suiteid", unique = true, nullable = false, length = 100)
	public String getSuiteid() {
		return this.suiteid;
	}

	public void setSuiteid(String suiteid) {
		this.suiteid = suiteid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business")
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "suitecode", nullable = false, length = 50)
	public String getSuitecode() {
		return this.suitecode;
	}

	public void setSuitecode(String suitecode) {
		this.suitecode = suitecode;
	}

	@Column(name = "gargroup", length = 35)
	public String getGargroup() {
		return this.gargroup;
	}

	public void setGargroup(String gargroup) {
		this.gargroup = gargroup;
	}

	@Column(name = "altphonenumber", length = 20)
	public String getAltphonenumber() {
		return this.altphonenumber;
	}

	public void setAltphonenumber(String altphonenumber) {
		this.altphonenumber = altphonenumber;
	}

	@Column(name = "phonenumber", length = 20)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "siteid")
	public Integer getSiteid() {
		return this.siteid;
	}

	public void setSiteid(Integer siteid) {
		this.siteid = siteid;
	}

	@Column(name = "suitename", nullable = false, length = 50)
	public String getSuitename() {
		return this.suitename;
	}

	public void setSuitename(String suitename) {
		this.suitename = suitename;
	}

	@Column(name = "scheduleid", length = 50)
	public String getScheduleid() {
		return this.scheduleid;
	}

	public void setScheduleid(String scheduleid) {
		this.scheduleid = scheduleid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suites")
	public Set<Suitefloorgroups> getSuitefloorgroupses() {
		return this.suitefloorgroupses;
	}

	public void setSuitefloorgroupses(Set<Suitefloorgroups> suitefloorgroupses) {
		this.suitefloorgroupses = suitefloorgroupses;
	}

}
