package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Systemports generated by hbm2java
 */
@Entity
@Table(name = "systemports", schema = "public")
public class Systemports implements java.io.Serializable {

	private String portname;
	private long id;
	private Long baudrate;
	private Long databits;
	private Long stopbits;
	private String portdescription;
	private Long incomingpollingperiod;
	private Long resendmultiplier;
	private Long silencebeforesend;
	private String protocolversion;
	private String peerportname;
	private int siteid;
	private Set<Devices> deviceses = new HashSet<Devices>(0);

	public Systemports() {
	}

	public Systemports(String portname, long id, String protocolversion, int siteid) {
		this.portname = portname;
		this.id = id;
		this.protocolversion = protocolversion;
		this.siteid = siteid;
	}

	public Systemports(String portname, long id, Long baudrate, Long databits, Long stopbits, String portdescription,
			Long incomingpollingperiod, Long resendmultiplier, Long silencebeforesend, String protocolversion,
			String peerportname, int siteid, Set<Devices> deviceses) {
		this.portname = portname;
		this.id = id;
		this.baudrate = baudrate;
		this.databits = databits;
		this.stopbits = stopbits;
		this.portdescription = portdescription;
		this.incomingpollingperiod = incomingpollingperiod;
		this.resendmultiplier = resendmultiplier;
		this.silencebeforesend = silencebeforesend;
		this.protocolversion = protocolversion;
		this.peerportname = peerportname;
		this.siteid = siteid;
		this.deviceses = deviceses;
	}

	@Id

	@Column(name = "portname", unique = true, nullable = false, length = 50)
	public String getPortname() {
		return this.portname;
	}

	public void setPortname(String portname) {
		this.portname = portname;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "baudrate")
	public Long getBaudrate() {
		return this.baudrate;
	}

	public void setBaudrate(Long baudrate) {
		this.baudrate = baudrate;
	}

	@Column(name = "databits")
	public Long getDatabits() {
		return this.databits;
	}

	public void setDatabits(Long databits) {
		this.databits = databits;
	}

	@Column(name = "stopbits")
	public Long getStopbits() {
		return this.stopbits;
	}

	public void setStopbits(Long stopbits) {
		this.stopbits = stopbits;
	}

	@Column(name = "portdescription", length = 50)
	public String getPortdescription() {
		return this.portdescription;
	}

	public void setPortdescription(String portdescription) {
		this.portdescription = portdescription;
	}

	@Column(name = "incomingpollingperiod")
	public Long getIncomingpollingperiod() {
		return this.incomingpollingperiod;
	}

	public void setIncomingpollingperiod(Long incomingpollingperiod) {
		this.incomingpollingperiod = incomingpollingperiod;
	}

	@Column(name = "resendmultiplier")
	public Long getResendmultiplier() {
		return this.resendmultiplier;
	}

	public void setResendmultiplier(Long resendmultiplier) {
		this.resendmultiplier = resendmultiplier;
	}

	@Column(name = "silencebeforesend")
	public Long getSilencebeforesend() {
		return this.silencebeforesend;
	}

	public void setSilencebeforesend(Long silencebeforesend) {
		this.silencebeforesend = silencebeforesend;
	}

	@Column(name = "protocolversion", nullable = false, length = 50)
	public String getProtocolversion() {
		return this.protocolversion;
	}

	public void setProtocolversion(String protocolversion) {
		this.protocolversion = protocolversion;
	}

	@Column(name = "peerportname", length = 50)
	public String getPeerportname() {
		return this.peerportname;
	}

	public void setPeerportname(String peerportname) {
		this.peerportname = peerportname;
	}

	@Column(name = "siteid", nullable = false)
	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemports")
	public Set<Devices> getDeviceses() {
		return this.deviceses;
	}

	public void setDeviceses(Set<Devices> deviceses) {
		this.deviceses = deviceses;
	}

}
