package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tiareport generated by hbm2java
 */
@Entity
@Table(name = "tiareport", schema = "public")
public class Tiareport implements java.io.Serializable {

	private long id;
	private Long rptId;
	private String userid;
	private String suiteid;
	private String cardnumber;
	private String firstname;
	private String lastname;
	private Date inTime;
	private String inDev;
	private Date exitTime;
	private String exitDev;
	private Long duration;

	public Tiareport() {
	}

	public Tiareport(long id) {
		this.id = id;
	}

	public Tiareport(long id, Long rptId, String userid, String suiteid, String cardnumber, String firstname,
			String lastname, Date inTime, String inDev, Date exitTime, String exitDev, Long duration) {
		this.id = id;
		this.rptId = rptId;
		this.userid = userid;
		this.suiteid = suiteid;
		this.cardnumber = cardnumber;
		this.firstname = firstname;
		this.lastname = lastname;
		this.inTime = inTime;
		this.inDev = inDev;
		this.exitTime = exitTime;
		this.exitDev = exitDev;
		this.duration = duration;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "rpt_id")
	public Long getRptId() {
		return this.rptId;
	}

	public void setRptId(Long rptId) {
		this.rptId = rptId;
	}

	@Column(name = "userid", length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "suiteid", length = 50)
	public String getSuiteid() {
		return this.suiteid;
	}

	public void setSuiteid(String suiteid) {
		this.suiteid = suiteid;
	}

	@Column(name = "cardnumber", length = 20)
	public String getCardnumber() {
		return this.cardnumber;
	}

	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "in_time", length = 29)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	@Column(name = "in_dev", length = 100)
	public String getInDev() {
		return this.inDev;
	}

	public void setInDev(String inDev) {
		this.inDev = inDev;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exit_time", length = 29)
	public Date getExitTime() {
		return this.exitTime;
	}

	public void setExitTime(Date exitTime) {
		this.exitTime = exitTime;
	}

	@Column(name = "exit_dev", length = 100)
	public String getExitDev() {
		return this.exitDev;
	}

	public void setExitDev(String exitDev) {
		this.exitDev = exitDev;
	}

	@Column(name = "duration")
	public Long getDuration() {
		return this.duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

}
