package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Userldapgroups generated by hbm2java
 */
@Entity
@Table(name = "userldapgroups", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "userid",
		"ldapgroupid" }))
public class Userldapgroups implements java.io.Serializable {

	private int id;
	private Ldapgroups ldapgroups;
	private Users users;

	public Userldapgroups() {
	}

	public Userldapgroups(int id, Ldapgroups ldapgroups, Users users) {
		this.id = id;
		this.ldapgroups = ldapgroups;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ldapgroupid", nullable = false)
	public Ldapgroups getLdapgroups() {
		return this.ldapgroups;
	}

	public void setLdapgroups(Ldapgroups ldapgroups) {
		this.ldapgroups = ldapgroups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
