package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Useraccessrights generated by hbm2java
 */
@Entity
@Table(name = "useraccessrights", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "rarid",
		"zoneid" }))
public class Useraccessrights implements java.io.Serializable {

	private long id;
	private Rargroup rargroup;
	private Schedule schedule;
	private Zones zones;
	private Integer activationtime;
	private Date lastaccesstime;
	private Long usnchanged;
	private String uarid;

	public Useraccessrights() {
	}

	public Useraccessrights(long id, Rargroup rargroup, Schedule schedule, Zones zones) {
		this.id = id;
		this.rargroup = rargroup;
		this.schedule = schedule;
		this.zones = zones;
	}

	public Useraccessrights(long id, Rargroup rargroup, Schedule schedule, Zones zones, Integer activationtime,
			Date lastaccesstime, Long usnchanged, String uarid) {
		this.id = id;
		this.rargroup = rargroup;
		this.schedule = schedule;
		this.zones = zones;
		this.activationtime = activationtime;
		this.lastaccesstime = lastaccesstime;
		this.usnchanged = usnchanged;
		this.uarid = uarid;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rarid", nullable = false)
	public Rargroup getRargroup() {
		return this.rargroup;
	}

	public void setRargroup(Rargroup rargroup) {
		this.rargroup = rargroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scheduleid", nullable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zoneid", nullable = false)
	public Zones getZones() {
		return this.zones;
	}

	public void setZones(Zones zones) {
		this.zones = zones;
	}

	@Column(name = "activationtime")
	public Integer getActivationtime() {
		return this.activationtime;
	}

	public void setActivationtime(Integer activationtime) {
		this.activationtime = activationtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastaccesstime", length = 29)
	public Date getLastaccesstime() {
		return this.lastaccesstime;
	}

	public void setLastaccesstime(Date lastaccesstime) {
		this.lastaccesstime = lastaccesstime;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@Column(name = "uarid", length = 200)
	public String getUarid() {
		return this.uarid;
	}

	public void setUarid(String uarid) {
		this.uarid = uarid;
	}

}
