package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "userid"))
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Ldaporganizationunits ldaporganizationunits;
	private String userid;
	private String firstname;
	private String lastname;
	private String suitenumber;
	private String carddata;
	private String cardnumber;
	private String pin;
	private long usertype;
	private String displayname;
	private String rargroup;
	private Long expire;
	private String wgcarddata;
	private Integer displayuser;
	private Long startdate;
	private String adminid;
	private Long lastupdate;
	private String lastreaderid;
	private Integer lastreaderport;
	private String lastzoneid;
	private Date lastaccess;
	private Long usnchanged;
	private Long usncardchanged;
	private String email;
	private String telephone;
	private Boolean accountdisabled;
	private Date createdAt;
	private Date updatedAt;
	private Integer usercategory;
	private Boolean accessibility;
	private Long cardtemplateid;
	private Set<Credentials> credentialses = new HashSet<Credentials>(0);
	private Set<Useraccessgroups> useraccessgroupses = new HashSet<Useraccessgroups>(0);
	private Set<Carddata> carddatas = new HashSet<Carddata>(0);
	private Set<Flooraccessgroups> flooraccessgroupses = new HashSet<Flooraccessgroups>(0);
	private Usernotes usernotes;
	private Set<Images> imageses = new HashSet<Images>(0);
	private Set<Sausers> sauserses = new HashSet<Sausers>(0);
	private Set<Userldapgroups> userldapgroupses = new HashSet<Userldapgroups>(0);
	private Set<Zoneusers> zoneuserses = new HashSet<Zoneusers>(0);

	public Users() {
	}

	public Users(int id, String userid, long usertype, Date createdAt, Date updatedAt) {
		this.id = id;
		this.userid = userid;
		this.usertype = usertype;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Users(int id, Ldaporganizationunits ldaporganizationunits, String userid, String firstname, String lastname,
			String suitenumber, String carddata, String cardnumber, String pin, long usertype, String displayname,
			String rargroup, Long expire, String wgcarddata, Integer displayuser, Long startdate, String adminid,
			Long lastupdate, String lastreaderid, Integer lastreaderport, String lastzoneid, Date lastaccess,
			Long usnchanged, Long usncardchanged, String email, String telephone, Boolean accountdisabled,
			Date createdAt, Date updatedAt, Integer usercategory, Boolean accessibility, Long cardtemplateid,
			Set<Credentials> credentialses, Set<Useraccessgroups> useraccessgroupses, Set<Carddata> carddatas,
			Set<Flooraccessgroups> flooraccessgroupses, Usernotes usernotes, Set<Images> imageses,
			Set<Sausers> sauserses, Set<Userldapgroups> userldapgroupses, Set<Zoneusers> zoneuserses) {
		this.id = id;
		this.ldaporganizationunits = ldaporganizationunits;
		this.userid = userid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.suitenumber = suitenumber;
		this.carddata = carddata;
		this.cardnumber = cardnumber;
		this.pin = pin;
		this.usertype = usertype;
		this.displayname = displayname;
		this.rargroup = rargroup;
		this.expire = expire;
		this.wgcarddata = wgcarddata;
		this.displayuser = displayuser;
		this.startdate = startdate;
		this.adminid = adminid;
		this.lastupdate = lastupdate;
		this.lastreaderid = lastreaderid;
		this.lastreaderport = lastreaderport;
		this.lastzoneid = lastzoneid;
		this.lastaccess = lastaccess;
		this.usnchanged = usnchanged;
		this.usncardchanged = usncardchanged;
		this.email = email;
		this.telephone = telephone;
		this.accountdisabled = accountdisabled;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.usercategory = usercategory;
		this.accessibility = accessibility;
		this.cardtemplateid = cardtemplateid;
		this.credentialses = credentialses;
		this.useraccessgroupses = useraccessgroupses;
		this.carddatas = carddatas;
		this.flooraccessgroupses = flooraccessgroupses;
		this.usernotes = usernotes;
		this.imageses = imageses;
		this.sauserses = sauserses;
		this.userldapgroupses = userldapgroupses;
		this.zoneuserses = zoneuserses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ou")
	public Ldaporganizationunits getLdaporganizationunits() {
		return this.ldaporganizationunits;
	}

	public void setLdaporganizationunits(Ldaporganizationunits ldaporganizationunits) {
		this.ldaporganizationunits = ldaporganizationunits;
	}

	@Column(name = "userid", unique = true, nullable = false, length = 200)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "suitenumber", length = 100)
	public String getSuitenumber() {
		return this.suitenumber;
	}

	public void setSuitenumber(String suitenumber) {
		this.suitenumber = suitenumber;
	}

	@Column(name = "carddata", length = 100)
	public String getCarddata() {
		return this.carddata;
	}

	public void setCarddata(String carddata) {
		this.carddata = carddata;
	}

	@Column(name = "cardnumber", length = 50)
	public String getCardnumber() {
		return this.cardnumber;
	}

	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}

	@Column(name = "pin", length = 50)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "usertype", nullable = false)
	public long getUsertype() {
		return this.usertype;
	}

	public void setUsertype(long usertype) {
		this.usertype = usertype;
	}

	@Column(name = "displayname", length = 50)
	public String getDisplayname() {
		return this.displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	@Column(name = "rargroup", length = 35)
	public String getRargroup() {
		return this.rargroup;
	}

	public void setRargroup(String rargroup) {
		this.rargroup = rargroup;
	}

	@Column(name = "expire")
	public Long getExpire() {
		return this.expire;
	}

	public void setExpire(Long expire) {
		this.expire = expire;
	}

	@Column(name = "wgcarddata", length = 100)
	public String getWgcarddata() {
		return this.wgcarddata;
	}

	public void setWgcarddata(String wgcarddata) {
		this.wgcarddata = wgcarddata;
	}

	@Column(name = "displayuser")
	public Integer getDisplayuser() {
		return this.displayuser;
	}

	public void setDisplayuser(Integer displayuser) {
		this.displayuser = displayuser;
	}

	@Column(name = "startdate")
	public Long getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Long startdate) {
		this.startdate = startdate;
	}

	@Column(name = "adminid", length = 50)
	public String getAdminid() {
		return this.adminid;
	}

	public void setAdminid(String adminid) {
		this.adminid = adminid;
	}

	@Column(name = "lastupdate")
	public Long getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Long lastupdate) {
		this.lastupdate = lastupdate;
	}

	@Column(name = "lastreaderid", length = 100)
	public String getLastreaderid() {
		return this.lastreaderid;
	}

	public void setLastreaderid(String lastreaderid) {
		this.lastreaderid = lastreaderid;
	}

	@Column(name = "lastreaderport")
	public Integer getLastreaderport() {
		return this.lastreaderport;
	}

	public void setLastreaderport(Integer lastreaderport) {
		this.lastreaderport = lastreaderport;
	}

	@Column(name = "lastzoneid", length = 200)
	public String getLastzoneid() {
		return this.lastzoneid;
	}

	public void setLastzoneid(String lastzoneid) {
		this.lastzoneid = lastzoneid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastaccess", length = 29)
	public Date getLastaccess() {
		return this.lastaccess;
	}

	public void setLastaccess(Date lastaccess) {
		this.lastaccess = lastaccess;
	}

	@Column(name = "usnchanged")
	public Long getUsnchanged() {
		return this.usnchanged;
	}

	public void setUsnchanged(Long usnchanged) {
		this.usnchanged = usnchanged;
	}

	@Column(name = "usncardchanged")
	public Long getUsncardchanged() {
		return this.usncardchanged;
	}

	public void setUsncardchanged(Long usncardchanged) {
		this.usncardchanged = usncardchanged;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", length = 50)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "accountdisabled")
	public Boolean getAccountdisabled() {
		return this.accountdisabled;
	}

	public void setAccountdisabled(Boolean accountdisabled) {
		this.accountdisabled = accountdisabled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "usercategory")
	public Integer getUsercategory() {
		return this.usercategory;
	}

	public void setUsercategory(Integer usercategory) {
		this.usercategory = usercategory;
	}

	@Column(name = "accessibility")
	public Boolean getAccessibility() {
		return this.accessibility;
	}

	public void setAccessibility(Boolean accessibility) {
		this.accessibility = accessibility;
	}

	@Column(name = "cardtemplateid")
	public Long getCardtemplateid() {
		return this.cardtemplateid;
	}

	public void setCardtemplateid(Long cardtemplateid) {
		this.cardtemplateid = cardtemplateid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Credentials> getCredentialses() {
		return this.credentialses;
	}

	public void setCredentialses(Set<Credentials> credentialses) {
		this.credentialses = credentialses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Useraccessgroups> getUseraccessgroupses() {
		return this.useraccessgroupses;
	}

	public void setUseraccessgroupses(Set<Useraccessgroups> useraccessgroupses) {
		this.useraccessgroupses = useraccessgroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Carddata> getCarddatas() {
		return this.carddatas;
	}

	public void setCarddatas(Set<Carddata> carddatas) {
		this.carddatas = carddatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Flooraccessgroups> getFlooraccessgroupses() {
		return this.flooraccessgroupses;
	}

	public void setFlooraccessgroupses(Set<Flooraccessgroups> flooraccessgroupses) {
		this.flooraccessgroupses = flooraccessgroupses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Usernotes getUsernotes() {
		return this.usernotes;
	}

	public void setUsernotes(Usernotes usernotes) {
		this.usernotes = usernotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Images> getImageses() {
		return this.imageses;
	}

	public void setImageses(Set<Images> imageses) {
		this.imageses = imageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Sausers> getSauserses() {
		return this.sauserses;
	}

	public void setSauserses(Set<Sausers> sauserses) {
		this.sauserses = sauserses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Userldapgroups> getUserldapgroupses() {
		return this.userldapgroupses;
	}

	public void setUserldapgroupses(Set<Userldapgroups> userldapgroupses) {
		this.userldapgroupses = userldapgroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Zoneusers> getZoneuserses() {
		return this.zoneuserses;
	}

	public void setZoneuserses(Set<Zoneusers> zoneuserses) {
		this.zoneuserses = zoneuserses;
	}

}
