package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usercategories generated by hbm2java
 */
@Entity
@Table(name = "usercategories", schema = "public")
public class Usercategories implements java.io.Serializable {

	private int catId;
	private String catName;
	private Integer sortOrder;

	public Usercategories() {
	}

	public Usercategories(int catId) {
		this.catId = catId;
	}

	public Usercategories(int catId, String catName, Integer sortOrder) {
		this.catId = catId;
		this.catName = catName;
		this.sortOrder = sortOrder;
	}

	@Id

	@Column(name = "cat_id", unique = true, nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	@Column(name = "cat_name", length = 50)
	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	@Column(name = "sort_order")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
