package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Zonedevices generated by hbm2java
 */
@Entity
@Table(name = "zonedevices", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "zoneid",
		"deviceid", "portnumber" }))
public class Zonedevices implements java.io.Serializable {

	private long id;
	private Devices devices;
	private Zones zones;
	private long portnumber;
	private String iocontrol;
	private Boolean defaultactivation;
	private Integer delay;
	private Integer activationtime;
	private Integer portusage;
	private Boolean allowlatch;
	private Integer accDelay;
	private Integer accActivationtime;

	public Zonedevices() {
	}

	public Zonedevices(long id, Devices devices, Zones zones, long portnumber) {
		this.id = id;
		this.devices = devices;
		this.zones = zones;
		this.portnumber = portnumber;
	}

	public Zonedevices(long id, Devices devices, Zones zones, long portnumber, String iocontrol,
			Boolean defaultactivation, Integer delay, Integer activationtime, Integer portusage, Boolean allowlatch,
			Integer accDelay, Integer accActivationtime) {
		this.id = id;
		this.devices = devices;
		this.zones = zones;
		this.portnumber = portnumber;
		this.iocontrol = iocontrol;
		this.defaultactivation = defaultactivation;
		this.delay = delay;
		this.activationtime = activationtime;
		this.portusage = portusage;
		this.allowlatch = allowlatch;
		this.accDelay = accDelay;
		this.accActivationtime = accActivationtime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceid", nullable = false)
	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zoneid", nullable = false)
	public Zones getZones() {
		return this.zones;
	}

	public void setZones(Zones zones) {
		this.zones = zones;
	}

	@Column(name = "portnumber", nullable = false)
	public long getPortnumber() {
		return this.portnumber;
	}

	public void setPortnumber(long portnumber) {
		this.portnumber = portnumber;
	}

	@Column(name = "iocontrol", length = 2)
	public String getIocontrol() {
		return this.iocontrol;
	}

	public void setIocontrol(String iocontrol) {
		this.iocontrol = iocontrol;
	}

	@Column(name = "defaultactivation")
	public Boolean getDefaultactivation() {
		return this.defaultactivation;
	}

	public void setDefaultactivation(Boolean defaultactivation) {
		this.defaultactivation = defaultactivation;
	}

	@Column(name = "delay")
	public Integer getDelay() {
		return this.delay;
	}

	public void setDelay(Integer delay) {
		this.delay = delay;
	}

	@Column(name = "activationtime")
	public Integer getActivationtime() {
		return this.activationtime;
	}

	public void setActivationtime(Integer activationtime) {
		this.activationtime = activationtime;
	}

	@Column(name = "portusage")
	public Integer getPortusage() {
		return this.portusage;
	}

	public void setPortusage(Integer portusage) {
		this.portusage = portusage;
	}

	@Column(name = "allowlatch")
	public Boolean getAllowlatch() {
		return this.allowlatch;
	}

	public void setAllowlatch(Boolean allowlatch) {
		this.allowlatch = allowlatch;
	}

	@Column(name = "acc_delay")
	public Integer getAccDelay() {
		return this.accDelay;
	}

	public void setAccDelay(Integer accDelay) {
		this.accDelay = accDelay;
	}

	@Column(name = "acc_activationtime")
	public Integer getAccActivationtime() {
		return this.accActivationtime;
	}

	public void setAccActivationtime(Integer accActivationtime) {
		this.accActivationtime = accActivationtime;
	}

}
