package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Zonegroupexempt generated by hbm2java
 */
@Entity
@Table(name = "zonegroupexempt", schema = "public")
public class Zonegroupexempt implements java.io.Serializable {

	private int id;
	private Rargroup rargroup;
	private Zonegroups zonegroups;

	public Zonegroupexempt() {
	}

	public Zonegroupexempt(int id, Rargroup rargroup, Zonegroups zonegroups) {
		this.id = id;
		this.rargroup = rargroup;
		this.zonegroups = zonegroups;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rargroup", nullable = false)
	public Rargroup getRargroup() {
		return this.rargroup;
	}

	public void setRargroup(Rargroup rargroup) {
		this.rargroup = rargroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zonegroupid", nullable = false)
	public Zonegroups getZonegroups() {
		return this.zonegroups;
	}

	public void setZonegroups(Zonegroups zonegroups) {
		this.zonegroups = zonegroups;
	}

}
