package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Zonegroupzones generated by hbm2java
 */
@Entity
@Table(name = "zonegroupzones", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "zonegroupid",
		"zoneid" }))
public class Zonegroupzones implements java.io.Serializable {

	private int id;
	private Zonegroups zonegroups;
	private Zones zones;

	public Zonegroupzones() {
	}

	public Zonegroupzones(int id, Zonegroups zonegroups, Zones zones) {
		this.id = id;
		this.zonegroups = zonegroups;
		this.zones = zones;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zonegroupid", nullable = false)
	public Zonegroups getZonegroups() {
		return this.zonegroups;
	}

	public void setZonegroups(Zonegroups zonegroups) {
		this.zonegroups = zonegroups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zoneid", nullable = false)
	public Zones getZones() {
		return this.zones;
	}

	public void setZones(Zones zones) {
		this.zones = zones;
	}

}
