package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Zonelinks generated by hbm2java
 */
@Entity
@Table(name = "zonelinks", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "zoneid",
		"child_zoneid" }))
public class Zonelinks implements java.io.Serializable {

	private long id;
	private Zones zonesByZoneid;
	private Zones zonesByChildZoneid;
	private Integer delay;
	private Integer activationtime;
	private Integer accDelay;
	private Integer accActivationtime;

	public Zonelinks() {
	}

	public Zonelinks(long id, Zones zonesByZoneid, Zones zonesByChildZoneid) {
		this.id = id;
		this.zonesByZoneid = zonesByZoneid;
		this.zonesByChildZoneid = zonesByChildZoneid;
	}

	public Zonelinks(long id, Zones zonesByZoneid, Zones zonesByChildZoneid, Integer delay, Integer activationtime,
			Integer accDelay, Integer accActivationtime) {
		this.id = id;
		this.zonesByZoneid = zonesByZoneid;
		this.zonesByChildZoneid = zonesByChildZoneid;
		this.delay = delay;
		this.activationtime = activationtime;
		this.accDelay = accDelay;
		this.accActivationtime = accActivationtime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zoneid", nullable = false)
	public Zones getZonesByZoneid() {
		return this.zonesByZoneid;
	}

	public void setZonesByZoneid(Zones zonesByZoneid) {
		this.zonesByZoneid = zonesByZoneid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "child_zoneid", nullable = false)
	public Zones getZonesByChildZoneid() {
		return this.zonesByChildZoneid;
	}

	public void setZonesByChildZoneid(Zones zonesByChildZoneid) {
		this.zonesByChildZoneid = zonesByChildZoneid;
	}

	@Column(name = "delay")
	public Integer getDelay() {
		return this.delay;
	}

	public void setDelay(Integer delay) {
		this.delay = delay;
	}

	@Column(name = "activationtime")
	public Integer getActivationtime() {
		return this.activationtime;
	}

	public void setActivationtime(Integer activationtime) {
		this.activationtime = activationtime;
	}

	@Column(name = "acc_delay")
	public Integer getAccDelay() {
		return this.accDelay;
	}

	public void setAccDelay(Integer accDelay) {
		this.accDelay = accDelay;
	}

	@Column(name = "acc_activationtime")
	public Integer getAccActivationtime() {
		return this.accActivationtime;
	}

	public void setAccActivationtime(Integer accActivationtime) {
		this.accActivationtime = accActivationtime;
	}

}
