package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Zoneusers generated by hbm2java
 */
@Entity
@Table(name = "zoneusers", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "userid",
		"zonegroupid" }))
public class Zoneusers implements java.io.Serializable {

	private int id;
	private Users users;
	private Zonegroups zonegroups;
	private Date accesstime;
	private Boolean inzone;
	private String zoneid;
	private String readerid;
	private Integer readerport;
	private Boolean apbActive;

	public Zoneusers() {
	}

	public Zoneusers(int id, Users users, Zonegroups zonegroups, Date accesstime) {
		this.id = id;
		this.users = users;
		this.zonegroups = zonegroups;
		this.accesstime = accesstime;
	}

	public Zoneusers(int id, Users users, Zonegroups zonegroups, Date accesstime, Boolean inzone, String zoneid,
			String readerid, Integer readerport, Boolean apbActive) {
		this.id = id;
		this.users = users;
		this.zonegroups = zonegroups;
		this.accesstime = accesstime;
		this.inzone = inzone;
		this.zoneid = zoneid;
		this.readerid = readerid;
		this.readerport = readerport;
		this.apbActive = apbActive;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zonegroupid", nullable = false)
	public Zonegroups getZonegroups() {
		return this.zonegroups;
	}

	public void setZonegroups(Zonegroups zonegroups) {
		this.zonegroups = zonegroups;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "accesstime", nullable = false, length = 29)
	public Date getAccesstime() {
		return this.accesstime;
	}

	public void setAccesstime(Date accesstime) {
		this.accesstime = accesstime;
	}

	@Column(name = "inzone")
	public Boolean getInzone() {
		return this.inzone;
	}

	public void setInzone(Boolean inzone) {
		this.inzone = inzone;
	}

	@Column(name = "zoneid", length = 200)
	public String getZoneid() {
		return this.zoneid;
	}

	public void setZoneid(String zoneid) {
		this.zoneid = zoneid;
	}

	@Column(name = "readerid")
	public String getReaderid() {
		return this.readerid;
	}

	public void setReaderid(String readerid) {
		this.readerid = readerid;
	}

	@Column(name = "readerport")
	public Integer getReaderport() {
		return this.readerport;
	}

	public void setReaderport(Integer readerport) {
		this.readerport = readerport;
	}

	@Column(name = "apb_active")
	public Boolean getApbActive() {
		return this.apbActive;
	}

	public void setApbActive(Boolean apbActive) {
		this.apbActive = apbActive;
	}

}
