package com.viscount.freedom.domains;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Zoneidspanels generated by hbm2java
 */
@Entity
@Table(name = "zoneidspanels", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "zoneid",
		"ids_id" }))
public class Zoneidspanels implements java.io.Serializable {

	private long idsId;
	private String zoneid;
	private Integer disarmPeriod;

	public Zoneidspanels() {
	}

	public Zoneidspanels(long idsId, String zoneid) {
		this.idsId = idsId;
		this.zoneid = zoneid;
	}

	public Zoneidspanels(long idsId, String zoneid, Integer disarmPeriod) {
		this.idsId = idsId;
		this.zoneid = zoneid;
		this.disarmPeriod = disarmPeriod;
	}

	@Id

	@Column(name = "ids_id", unique = true, nullable = false)
	public long getIdsId() {
		return this.idsId;
	}

	public void setIdsId(long idsId) {
		this.idsId = idsId;
	}

	@Column(name = "zoneid", nullable = false, length = 200)
	public String getZoneid() {
		return this.zoneid;
	}

	public void setZoneid(String zoneid) {
		this.zoneid = zoneid;
	}

	@Column(name = "disarm_period")
	public Integer getDisarmPeriod() {
		return this.disarmPeriod;
	}

	public void setDisarmPeriod(Integer disarmPeriod) {
		this.disarmPeriod = disarmPeriod;
	}

}
