package com.viscount.freedom.user.domain;
// Generated Mar 2, 2016 10:13:57 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Useraccessgroups generated by hbm2java
 */
@Entity
@Table(name = "useraccessgroups", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "userid",
		"rargroup" }))
public class Useraccessgroups implements java.io.Serializable {

	private long id;
	//private Rargroup rargroup;
	private Users users;
	private Boolean alwayson;
	private Date startdate;
	private Date enddate;

	public Useraccessgroups() {
	}

	public Useraccessgroups(long id) {
		this.id = id;
	}

	public Useraccessgroups(long id,  Users users, Boolean alwayson, Date startdate, Date enddate) {
		this.id = id;
		//this.rargroup = rargroup;
		this.users = users;
		this.alwayson = alwayson;
		this.startdate = startdate;
		this.enddate = enddate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rargroup")
	public Rargroup getRargroup() {
		return this.rargroup;
	}

	public void setRargroup(Rargroup rargroup) {
		this.rargroup = rargroup;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "alwayson")
	public Boolean getAlwayson() {
		return this.alwayson;
	}

	public void setAlwayson(Boolean alwayson) {
		this.alwayson = alwayson;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdate", length = 29)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enddate", length = 29)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

}
